// This file is auto-generated by @hey-api/openapi-ts

export const AddContactCompanyCommandSchema = {
    title: 'AddContactCompanyCommand',
    required: [
        'id',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const AddLocationCompanyCommandSchema = {
    title: 'AddLocationCompanyCommand',
    required: [
        'id',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const AndersonAPI_Api_Controllers_ResponseTypes_JsonResponse_Of_GuidSchema = {
    title: 'AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Guid',
    required: [
        'value'
    ],
    type: 'object',
    properties: {
        value: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const ByteArraySchema = {
    title: 'ByteArray',
    type: 'string',
    format: 'byte',
    nullable: true
} as const;

export const CapabilityDtoSchema = {
    title: 'CapabilityDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyDtoSchema = {
    title: 'CompanyDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        embedding: {
            $ref: '#/components/schemas/ByteArray'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ConfirmEmailDtoSchema = {
    title: 'ConfirmEmailDto',
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            nullable: true
        },
        code: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CountryDtoSchema = {
    title: 'CountryDto',
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const CreateCapabilityCommandSchema = {
    title: 'CreateCapabilityCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateCompanyCommandSchema = {
    title: 'CreateCompanyCommand',
    required: [
        'name',
        'shortDescription',
        'fullDescription',
        'websiteUrl',
        'employeeCount',
        'serviceTypes',
        'capabilities',
        'industries'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const CreateCountryCommandSchema = {
    title: 'CreateCountryCommand',
    required: [
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateIndustryCommandSchema = {
    title: 'CreateIndustryCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateOppertunityTypeCommandSchema = {
    title: 'CreateOppertunityTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateRegionCommandSchema = {
    title: 'CreateRegionCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateServiceTypeCommandSchema = {
    title: 'CreateServiceTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const EntityStateSchema = {
    type: 'integer'
} as const;

export const ForgotPasswordDtoSchema = {
    title: 'ForgotPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const IndustryDtoSchema = {
    title: 'IndustryDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const InfoResponseDtoSchema = {
    title: 'InfoResponseDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const LoginDtoSchema = {
    title: 'LoginDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const OppertunityTypeDtoSchema = {
    title: 'OppertunityTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ProblemDetailsSchema = {
    title: 'ProblemDetails',
    type: 'object',
    properties: {
        type: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        detail: {
            type: 'string',
            nullable: true
        },
        instance: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RefreshTokenDtoSchema = {
    title: 'RefreshTokenDto',
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RegionDtoSchema = {
    title: 'RegionDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const RegisterDtoSchema = {
    title: 'RegisterDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const ResetPasswordDtoSchema = {
    title: 'ResetPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        resetCode: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const ServiceTypeDtoSchema = {
    title: 'ServiceTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetCapabilitiesCompanyCommandSchema = {
    title: 'SetCapabilitiesCompanyCommand',
    required: [
        'id',
        'capabilityIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        capabilityIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetHeadOfficeCompanyCommandSchema = {
    title: 'SetHeadOfficeCompanyCommand',
    required: [
        'id',
        'locationId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const SetIndustriesCompanyCommandSchema = {
    title: 'SetIndustriesCompanyCommand',
    required: [
        'id',
        'industryIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetServiceTypesCompanyCommandSchema = {
    title: 'SetServiceTypesCompanyCommand',
    required: [
        'id',
        'serviceTypeIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypeIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const TokenResultDtoSchema = {
    title: 'TokenResultDto',
    type: 'object',
    properties: {
        tokenType: {
            type: 'string',
            nullable: true
        },
        authenticationToken: {
            type: 'string',
            nullable: true
        },
        expiresIn: {
            type: 'integer',
            format: 'int32'
        },
        refreshToken: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCapabilityCommandSchema = {
    title: 'UpdateCapabilityCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateCompanyCommandSchema = {
    title: 'UpdateCompanyCommand',
    required: [
        'id',
        'name',
        'shortDescription',
        'description',
        'websiteUrl',
        'employeeCount'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UpdateContactCompanyCommandSchema = {
    title: 'UpdateContactCompanyCommand',
    required: [
        'id',
        'contactId',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        contactId: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCountryCommandSchema = {
    title: 'UpdateCountryCommand',
    required: [
        'id',
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateIndustryCommandSchema = {
    title: 'UpdateIndustryCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateInfoDtoSchema = {
    title: 'UpdateInfoDto',
    type: 'object',
    properties: {
        newEmail: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        },
        oldPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateLocationCompanyCommandSchema = {
    title: 'UpdateLocationCompanyCommand',
    required: [
        'id',
        'locationId',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const UpdateOppertunityTypeCommandSchema = {
    title: 'UpdateOppertunityTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateRegionCommandSchema = {
    title: 'UpdateRegionCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateServiceTypeCommandSchema = {
    title: 'UpdateServiceTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;
