// This file is auto-generated by @hey-api/openapi-ts

export const AddContactCompanyCommandSchema = {
    title: 'AddContactCompanyCommand',
    required: [
        'id',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const AddLocationCompanyCommandSchema = {
    title: 'AddLocationCompanyCommand',
    required: [
        'id',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const AddMessageOpportunityCommandSchema = {
    title: 'AddMessageOpportunityCommand',
    required: [
        'opportunityId',
        'content',
        'createdDate',
        'createdByUser',
        'createdByPartner'
    ],
    type: 'object',
    properties: {
        opportunityId: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        createdByUser: {
            type: 'string'
        },
        createdByPartner: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const AndersonAPI_Api_Controllers_ResponseTypes_JsonResponse_Of_GuidSchema = {
    title: 'AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Guid',
    required: [
        'value'
    ],
    type: 'object',
    properties: {
        value: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const CapabilityDtoSchema = {
    title: 'CapabilityDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyApplicationIdentityUserDtoSchema = {
    title: 'CompanyApplicationIdentityUserDto',
    type: 'object'
} as const;

export const CompanyCapabilityDtoSchema = {
    title: 'CompanyCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CompanyContactDtoSchema = {
    title: 'CompanyContactDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyDtoSchema = {
    title: 'CompanyDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyIndustryDtoSchema = {
    title: 'CompanyIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CompanyInviteDtoSchema = {
    title: 'CompanyInviteDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const CompanyLocationDtoSchema = {
    title: 'CompanyLocationDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        isHeadOffice: {
            type: 'boolean'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyProfileDtoSchema = {
    title: 'CompanyProfileDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        applicationIdentityUsers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyApplicationIdentityUserDto'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyCapabilityDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyServiceTypeDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyIndustryDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyContactDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyLocationDto'
            }
        },
        invites: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyInviteDto'
            }
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const CompanyServiceTypeDtoSchema = {
    title: 'CompanyServiceTypeDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ConfirmEmailDtoSchema = {
    title: 'ConfirmEmailDto',
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            nullable: true
        },
        code: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CountryDtoSchema = {
    title: 'CountryDto',
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const CreateCapabilityCommandSchema = {
    title: 'CreateCapabilityCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateCompanyCommandSchema = {
    title: 'CreateCompanyCommand',
    required: [
        'name',
        'shortDescription',
        'fullDescription',
        'websiteUrl',
        'employeeCount',
        'serviceTypes',
        'capabilities',
        'industries'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const CreateCountryCommandSchema = {
    title: 'CreateCountryCommand',
    required: [
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateIndustryCommandSchema = {
    title: 'CreateIndustryCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateOpportunityCommandSchema = {
    title: 'CreateOpportunityCommand',
    required: [
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId',
        'serviceTypes',
        'capabilities',
        'companyId',
        'industries'
    ],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const CreateOpportunityTypeCommandSchema = {
    title: 'CreateOpportunityTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateRegionCommandSchema = {
    title: 'CreateRegionCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateReviewCommandSchema = {
    title: 'CreateReviewCommand',
    required: [
        'comment',
        'rating',
        'applicationIdentityUserId',
        'reviewerCompanyId',
        'state'
    ],
    type: 'object',
    properties: {
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        applicationIdentityUserId: {
            type: 'string'
        },
        reviewerCompanyId: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const CreateServiceTypeCommandSchema = {
    title: 'CreateServiceTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const DirectoryProfileListItemSchema = {
    title: 'DirectoryProfileListItem',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerIndustryDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerServiceTypeDto'
            }
        }
    }
} as const;

export const EntityStateSchema = {
    type: 'integer'
} as const;

export const ForgotPasswordDtoSchema = {
    title: 'ForgotPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const GetPartnersByAIQuerySchema = {
    title: 'GetPartnersByAIQuery',
    required: [
        'query'
    ],
    type: 'object',
    properties: {
        query: {
            type: 'string'
        }
    }
} as const;

export const IndustryDtoSchema = {
    title: 'IndustryDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const InfoResponseDtoSchema = {
    title: 'InfoResponseDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const InterestedPartnerDtoSchema = {
    title: 'InterestedPartnerDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        }
    }
} as const;

export const LoginDtoSchema = {
    title: 'LoginDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const OpportunityCapabilityDtoSchema = {
    title: 'OpportunityCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityDtoSchema = {
    title: 'OpportunityDto',
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        country: {
            type: 'string'
        },
        opportunityType: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityCapabilityDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityIndustryDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityServiceTypeDto'
            }
        },
        status: {
            $ref: '#/components/schemas/OpportunityStatus'
        },
        shortDescription: {
            type: 'string'
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const OpportunityIndustryDtoSchema = {
    title: 'OpportunityIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityListItemDtoSchema = {
    title: 'OpportunityListItemDto',
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        companyName: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        country: {
            type: 'string'
        },
        opportunityTypeString: {
            type: 'string'
        },
        interestedPartners: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/InterestedPartnerDto'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityCapabilityDto'
            }
        }
    }
} as const;

export const OpportunityServiceTypeDtoSchema = {
    title: 'OpportunityServiceTypeDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityStatusSchema = {
    type: 'integer'
} as const;

export const OpportunityTypeDtoSchema = {
    title: 'OpportunityTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const PartnerCapabilityDtoSchema = {
    title: 'PartnerCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerContactDtoSchema = {
    title: 'PartnerContactDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PartnerIndustryDtoSchema = {
    title: 'PartnerIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerLocationDtoSchema = {
    title: 'PartnerLocationDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        isHeadOffice: {
            type: 'boolean'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        country: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const PartnerOpportunityDtoSchema = {
    title: 'PartnerOpportunityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        serviceTypes: {
            type: 'array',
            items: {
                title: 'PartnerServiceTypeDto'
            }
        },
        country: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/OpportunityStatus'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        opportunityType: {
            type: 'string'
        }
    }
} as const;

export const PartnerProfileSchema = {
    title: 'PartnerProfile',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerIndustryDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerServiceTypeDto'
            }
        },
        opportunities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerOpportunityDto'
            }
        },
        reviews: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerReviewDto'
            }
        }
    }
} as const;

export const PartnerProfileListItemSchema = {
    title: 'PartnerProfileListItem',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        matchScore: {
            type: 'number',
            format: 'double'
        }
    }
} as const;

export const PartnerReviewDtoSchema = {
    title: 'PartnerReviewDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        applicationIdentityUserId: {
            type: 'string'
        },
        reviewerCompanyId: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const PartnerServiceTypeDtoSchema = {
    title: 'PartnerServiceTypeDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ProblemDetailsSchema = {
    title: 'ProblemDetails',
    type: 'object',
    properties: {
        type: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        detail: {
            type: 'string',
            nullable: true
        },
        instance: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RefreshTokenDtoSchema = {
    title: 'RefreshTokenDto',
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RegionDtoSchema = {
    title: 'RegionDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const RegisterDtoSchema = {
    title: 'RegisterDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const ResetPasswordDtoSchema = {
    title: 'ResetPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        resetCode: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const ReviewDtoSchema = {
    title: 'ReviewDto',
    type: 'object',
    properties: {
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        applicationIdentityUserId: {
            type: 'string'
        },
        reviewerCompanyId: {
            type: 'string',
            format: 'uuid'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ScrapeWebsiteCommandSchema = {
    title: 'ScrapeWebsiteCommand',
    required: [
        'url'
    ],
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    }
} as const;

export const ServiceTypeDtoSchema = {
    title: 'ServiceTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetCapabilitiesCompanyCommandSchema = {
    title: 'SetCapabilitiesCompanyCommand',
    required: [
        'id',
        'capabilityIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        capabilityIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetCapabilitiesOpportunityCommandSchema = {
    title: 'SetCapabilitiesOpportunityCommand',
    required: [
        'id',
        'capabilityIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        capabilityIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetHeadOfficeCompanyCommandSchema = {
    title: 'SetHeadOfficeCompanyCommand',
    required: [
        'id',
        'locationId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const SetIndustriesCompanyCommandSchema = {
    title: 'SetIndustriesCompanyCommand',
    required: [
        'id',
        'industryIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetIndustriesOpportunityCommandSchema = {
    title: 'SetIndustriesOpportunityCommand',
    required: [
        'id',
        'industryIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetInterestedPartnersOpportunityCommandSchema = {
    title: 'SetInterestedPartnersOpportunityCommand',
    required: [
        'id',
        'companyIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        companyIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetServiceTypesCompanyCommandSchema = {
    title: 'SetServiceTypesCompanyCommand',
    required: [
        'id',
        'serviceTypeIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypeIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetServiceTypesOpportunityCommandSchema = {
    title: 'SetServiceTypesOpportunityCommand',
    required: [
        'id',
        'serviceTypeIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypeIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetStateCapabilityCommandSchema = {
    title: 'SetStateCapabilityCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateCompanyCommandSchema = {
    title: 'SetStateCompanyCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateCountryCommandSchema = {
    title: 'SetStateCountryCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateIndustryCommandSchema = {
    title: 'SetStateIndustryCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateOpportunityCommandSchema = {
    title: 'SetStateOpportunityCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateOpportunityTypeCommandSchema = {
    title: 'SetStateOpportunityTypeCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateRegionCommandSchema = {
    title: 'SetStateRegionCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateServiceTypeCommandSchema = {
    title: 'SetStateServiceTypeCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStatusOpportunityCommandSchema = {
    title: 'SetStatusOpportunityCommand',
    required: [
        'id',
        'statusOpportunityStatus'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        statusOpportunityStatus: {
            $ref: '#/components/schemas/OpportunityStatus'
        }
    }
} as const;

export const TokenResultDtoSchema = {
    title: 'TokenResultDto',
    type: 'object',
    properties: {
        tokenType: {
            type: 'string',
            nullable: true
        },
        authenticationToken: {
            type: 'string',
            nullable: true
        },
        expiresIn: {
            type: 'integer',
            format: 'int32'
        },
        refreshToken: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCapabilityCommandSchema = {
    title: 'UpdateCapabilityCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateCompanyCommandSchema = {
    title: 'UpdateCompanyCommand',
    required: [
        'id',
        'name',
        'shortDescription',
        'description',
        'websiteUrl',
        'employeeCount'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UpdateContactCompanyCommandSchema = {
    title: 'UpdateContactCompanyCommand',
    required: [
        'id',
        'contactId',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        contactId: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCountryCommandSchema = {
    title: 'UpdateCountryCommand',
    required: [
        'id',
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateFullOpportunityCommandSchema = {
    title: 'UpdateFullOpportunityCommand',
    required: [
        'id',
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId',
        'serviceTypes',
        'capabilities',
        'industries'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const UpdateIndustryCommandSchema = {
    title: 'UpdateIndustryCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateInfoDtoSchema = {
    title: 'UpdateInfoDto',
    type: 'object',
    properties: {
        newEmail: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        },
        oldPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateLocationCompanyCommandSchema = {
    title: 'UpdateLocationCompanyCommand',
    required: [
        'id',
        'locationId',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const UpdateMessageOpportunityCommandSchema = {
    title: 'UpdateMessageOpportunityCommand',
    required: [
        'id',
        'messageId',
        'content'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        messageId: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        }
    }
} as const;

export const UpdateOpportunityCommandSchema = {
    title: 'UpdateOpportunityCommand',
    required: [
        'id',
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const UpdateOpportunityTypeCommandSchema = {
    title: 'UpdateOpportunityTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateRegionCommandSchema = {
    title: 'UpdateRegionCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateReviewCommandSchema = {
    title: 'UpdateReviewCommand',
    required: [
        'id',
        'comment',
        'rating'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UpdateServiceTypeCommandSchema = {
    title: 'UpdateServiceTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;
