// This file is auto-generated by @hey-api/openapi-ts

export const AddContactCompanyCommandSchema = {
    title: 'AddContactCompanyCommand',
    required: [
        'id',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const AddInterestedPartnerOpportunityCommandSchema = {
    title: 'AddInterestedPartnerOpportunityCommand',
    required: [
        'id',
        'partnerId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        partnerId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const AddLocationCompanyCommandSchema = {
    title: 'AddLocationCompanyCommand',
    required: [
        'id',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const AddMessageOpportunityCommandSchema = {
    title: 'AddMessageOpportunityCommand',
    required: [
        'opportunityId',
        'content',
        'createdDate',
        'createdByUser',
        'createdByPartner',
        'createdByUserId',
        'isOwnMessage'
    ],
    type: 'object',
    properties: {
        opportunityId: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        createdByUser: {
            type: 'string'
        },
        createdByPartner: {
            type: 'string',
            nullable: true
        },
        createdByUserId: {
            type: 'string',
            format: 'uuid'
        },
        isOwnMessage: {
            type: 'boolean'
        }
    }
} as const;

export const AddReportLineQuarterlyCommandSchema = {
    title: 'AddReportLineQuarterlyCommand',
    required: [
        'id',
        'partnerCount',
        'headcount',
        'clientCount',
        'officeCount',
        'lawyerCount',
        'estimatedRevenue',
        'countryId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        partnerCount: {
            type: 'integer',
            format: 'int32'
        },
        headcount: {
            type: 'integer',
            format: 'int32'
        },
        clientCount: {
            type: 'integer',
            format: 'int32'
        },
        officeCount: {
            type: 'integer',
            format: 'int32'
        },
        lawyerCount: {
            type: 'integer',
            format: 'int32'
        },
        estimatedRevenue: {
            type: 'number',
            format: 'double'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const AddReportPartnerQuarterlyCommandSchema = {
    title: 'AddReportPartnerQuarterlyCommand',
    required: [
        'id',
        'name',
        'status'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/PartnerStatus'
        }
    }
} as const;

export const AndersonAPI_Api_Controllers_ResponseTypes_JsonResponse_Of_GuidSchema = {
    title: 'AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Guid',
    required: [
        'value'
    ],
    type: 'object',
    properties: {
        value: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const CapabilityDtoSchema = {
    title: 'CapabilityDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyCapabilityDtoSchema = {
    title: 'CompanyCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CompanyContactDtoSchema = {
    title: 'CompanyContactDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyDtoSchema = {
    title: 'CompanyDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        serviceTypeName: {
            type: 'string'
        }
    }
} as const;

export const CompanyIdentityUserDtoSchema = {
    title: 'CompanyIdentityUserDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        userName: {
            type: 'string'
        }
    }
} as const;

export const CompanyIndustryDtoSchema = {
    title: 'CompanyIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CompanyInviteDtoSchema = {
    title: 'CompanyInviteDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const CompanyLocationDtoSchema = {
    title: 'CompanyLocationDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        isHeadOffice: {
            type: 'boolean'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const CompanyProfileDtoSchema = {
    title: 'CompanyProfileDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        serviceTypeId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        serviceTypeName: {
            type: 'string'
        },
        applicationIdentityUsers: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyIdentityUserDto'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyCapabilityDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyIndustryDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyContactDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyLocationDto'
            }
        },
        invites: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CompanyInviteDto'
            }
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const ConfirmEmailDtoSchema = {
    title: 'ConfirmEmailDto',
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            nullable: true
        },
        code: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const CountryDtoSchema = {
    title: 'CountryDto',
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const CreateCapabilityCommandSchema = {
    title: 'CreateCapabilityCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateCompanyCommandSchema = {
    title: 'CreateCompanyCommand',
    required: [
        'name',
        'shortDescription',
        'fullDescription',
        'websiteUrl',
        'employeeCount',
        'capabilities',
        'industries',
        'serviceTypeId'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        serviceTypeId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        }
    }
} as const;

export const CreateCountryCommandSchema = {
    title: 'CreateCountryCommand',
    required: [
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateIndustryCommandSchema = {
    title: 'CreateIndustryCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateInviteCommandSchema = {
    title: 'CreateInviteCommand',
    required: [
        'email',
        'companyId'
    ],
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const CreateOpportunityCommandSchema = {
    title: 'CreateOpportunityCommand',
    required: [
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId',
        'serviceTypes',
        'capabilities',
        'companyId',
        'industries'
    ],
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const CreateOpportunityTypeCommandSchema = {
    title: 'CreateOpportunityTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateQuarterlyCommandSchema = {
    title: 'CreateQuarterlyCommand',
    required: [
        'year',
        'quarter',
        'companyId',
        'partners',
        'reports',
        'isSubmitted'
    ],
    type: 'object',
    properties: {
        year: {
            type: 'integer',
            format: 'int32'
        },
        quarter: {
            $ref: '#/components/schemas/ReportQuarter'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        partners: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateQuarterlyPartnersDto'
            }
        },
        reports: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/CreateQuarterlyReportsDto'
            }
        },
        isSubmitted: {
            type: 'boolean'
        }
    }
} as const;

export const CreateQuarterlyPartnersDtoSchema = {
    title: 'CreateQuarterlyPartnersDto',
    type: 'object',
    properties: {
        quaterlyId: {
            type: 'string',
            format: 'uuid'
        },
        status: {
            $ref: '#/components/schemas/PartnerStatus'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const CreateQuarterlyReportsDtoSchema = {
    title: 'CreateQuarterlyReportsDto',
    type: 'object',
    properties: {
        partnerCount: {
            type: 'integer',
            format: 'int32'
        },
        headcount: {
            type: 'integer',
            format: 'int32'
        },
        clientCount: {
            type: 'integer',
            format: 'int32'
        },
        officeCount: {
            type: 'integer',
            format: 'int32'
        },
        lawyerCount: {
            type: 'integer',
            format: 'int32'
        },
        estimatedRevenue: {
            type: 'number',
            format: 'double'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const CreateRegionCommandSchema = {
    title: 'CreateRegionCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CreateReviewCommandSchema = {
    title: 'CreateReviewCommand',
    required: [
        'comment',
        'rating',
        'applicationIdentityUserId',
        'reviewerCompanyId',
        'companyId'
    ],
    type: 'object',
    properties: {
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        applicationIdentityUserId: {
            type: 'string'
        },
        reviewerCompanyId: {
            type: 'string',
            format: 'uuid'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const CreateServiceTypeCommandSchema = {
    title: 'CreateServiceTypeCommand',
    required: [
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const DirectoryProfileListItemSchema = {
    title: 'DirectoryProfileListItem',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerIndustryDto'
            }
        },
        serviceTypeName: {
            type: 'string'
        }
    }
} as const;

export const EntityStateSchema = {
    type: 'integer'
} as const;

export const ForgotPasswordDtoSchema = {
    title: 'ForgotPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const GetPartnersByAIQuerySchema = {
    title: 'GetPartnersByAIQuery',
    required: [
        'query'
    ],
    type: 'object',
    properties: {
        query: {
            type: 'string'
        }
    }
} as const;

export const IndustryDtoSchema = {
    title: 'IndustryDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const InfoResponseDtoSchema = {
    title: 'InfoResponseDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const InterestedPartnerDtoSchema = {
    title: 'InterestedPartnerDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        }
    }
} as const;

export const InviteDtoSchema = {
    title: 'InviteDto',
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const LoginDtoSchema = {
    title: 'LoginDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const OpportunityCapabilityDtoSchema = {
    title: 'OpportunityCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityDtoSchema = {
    title: 'OpportunityDto',
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        country: {
            type: 'string'
        },
        opportunityType: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityCapabilityDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityIndustryDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityServiceTypeDto'
            }
        },
        status: {
            $ref: '#/components/schemas/OpportunityStatus'
        },
        shortDescription: {
            type: 'string'
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const OpportunityIndustryDtoSchema = {
    title: 'OpportunityIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityListItemDtoSchema = {
    title: 'OpportunityListItemDto',
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        companyName: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        country: {
            type: 'string'
        },
        opportunityTypeString: {
            type: 'string'
        },
        interestedPartners: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/InterestedPartnerDto'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityCapabilityDto'
            }
        }
    }
} as const;

export const OpportunityMessageDtoSchema = {
    title: 'OpportunityMessageDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        createdByUser: {
            type: 'string'
        },
        createdByPartner: {
            type: 'string',
            nullable: true
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        isOwnMessage: {
            type: 'boolean'
        },
        createdByUserId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const OpportunityServiceTypeDtoSchema = {
    title: 'OpportunityServiceTypeDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const OpportunityStatusSchema = {
    type: 'integer'
} as const;

export const OpportunityTypeDtoSchema = {
    title: 'OpportunityTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const OpportunityViewDtoSchema = {
    title: 'OpportunityViewDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        companyName: {
            type: 'string'
        },
        companyServiceType: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        country: {
            type: 'string'
        },
        opportunityType: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityCapabilityDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityIndustryDto'
            }
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityServiceTypeDto'
            }
        },
        status: {
            $ref: '#/components/schemas/OpportunityStatus'
        },
        interestedPartners: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/OpportunityViewPartnerDto'
            }
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const OpportunityViewPartnerDtoSchema = {
    title: 'OpportunityViewPartnerDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerCapabilityDtoSchema = {
    title: 'PartnerCapabilityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerContactDtoSchema = {
    title: 'PartnerContactDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PartnerIndustryDtoSchema = {
    title: 'PartnerIndustryDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerLocationDtoSchema = {
    title: 'PartnerLocationDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        isHeadOffice: {
            type: 'boolean'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        country: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        region: {
            type: 'string'
        }
    }
} as const;

export const PartnerOpportunityDtoSchema = {
    title: 'PartnerOpportunityDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        serviceTypes: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerServiceTypeDto'
            }
        },
        country: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/OpportunityStatus'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        opportunityType: {
            type: 'string'
        }
    }
} as const;

export const PartnerProfileDtoSchema = {
    title: 'PartnerProfileDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        industries: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerIndustryDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        opportunities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerOpportunityDto'
            }
        },
        serviceTypeId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        serviceTypeName: {
            type: 'string'
        }
    }
} as const;

export const PartnerProfileListItemSchema = {
    title: 'PartnerProfileListItem',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        capabilities: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerCapabilityDto'
            }
        },
        locations: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerLocationDto'
            }
        },
        contacts: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PartnerContactDto'
            }
        },
        matchScore: {
            type: 'number',
            format: 'double'
        }
    }
} as const;

export const PartnerServiceTypeDtoSchema = {
    title: 'PartnerServiceTypeDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const PartnerStatusSchema = {
    type: 'integer'
} as const;

export const ProblemDetailsSchema = {
    title: 'ProblemDetails',
    type: 'object',
    properties: {
        type: {
            type: 'string',
            nullable: true
        },
        title: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'integer',
            format: 'int32',
            nullable: true
        },
        detail: {
            type: 'string',
            nullable: true
        },
        instance: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const QuarterlyDtoSchema = {
    title: 'QuarterlyDto',
    type: 'object',
    properties: {
        quarter: {
            $ref: '#/components/schemas/ReportQuarter'
        },
        isSubmitted: {
            type: 'boolean'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        year: {
            type: 'integer',
            format: 'int32'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        revenue: {
            type: 'number',
            format: 'double'
        },
        headcount: {
            type: 'integer',
            format: 'int32'
        },
        submittedDate: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const QuarterlyReportDtoSchema = {
    title: 'QuarterlyReportDto',
    type: 'object',
    properties: {
        year: {
            type: 'integer',
            format: 'int32'
        },
        quarter: {
            $ref: '#/components/schemas/ReportQuarter'
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        isSubmitted: {
            type: 'boolean'
        },
        submittedDate: {
            type: 'string',
            format: 'date-time'
        },
        partners: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/QuarterlyReportPartnerDto'
            }
        },
        reportLines: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/QuarterlyReportLineDto'
            }
        }
    }
} as const;

export const QuarterlyReportLineDtoSchema = {
    title: 'QuarterlyReportLineDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        partnerCount: {
            type: 'integer',
            format: 'int32'
        },
        headcount: {
            type: 'integer',
            format: 'int32'
        },
        clientCount: {
            type: 'integer',
            format: 'int32'
        },
        officeCount: {
            type: 'integer',
            format: 'int32'
        },
        lawyerCount: {
            type: 'integer',
            format: 'int32'
        },
        estimatedRevenue: {
            type: 'number',
            format: 'double'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const QuarterlyReportPartnerDtoSchema = {
    title: 'QuarterlyReportPartnerDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        status: {
            $ref: '#/components/schemas/PartnerStatus'
        },
        name: {
            type: 'string'
        }
    }
} as const;

export const RefreshTokenDtoSchema = {
    title: 'RefreshTokenDto',
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RegionDtoSchema = {
    title: 'RegionDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const RegisterDtoSchema = {
    title: 'RegisterDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        },
        userName: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const RemoveInterestedPartnerOpportunityCommandSchema = {
    title: 'RemoveInterestedPartnerOpportunityCommand',
    required: [
        'id',
        'partnerId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        partnerId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const ReportQuarterSchema = {
    type: 'integer'
} as const;

export const ResetPasswordDtoSchema = {
    title: 'ResetPasswordDto',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            nullable: true
        },
        resetCode: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const ReviewDtoSchema = {
    title: 'ReviewDto',
    type: 'object',
    properties: {
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        },
        userId: {
            type: 'string'
        },
        createdByUserName: {
            type: 'string',
            nullable: true
        },
        createdDate: {
            type: 'string',
            format: 'date-time'
        },
        reviewerCompanyId: {
            type: 'string',
            format: 'uuid'
        },
        reviewerCompanyName: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const ScrapeWebsiteCommandSchema = {
    title: 'ScrapeWebsiteCommand',
    required: [
        'url'
    ],
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    }
} as const;

export const ServiceTypeDtoSchema = {
    title: 'ServiceTypeDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        order: {
            type: 'integer',
            format: 'int32'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetCapabilitiesCompanyCommandSchema = {
    title: 'SetCapabilitiesCompanyCommand',
    required: [
        'id',
        'capabilityIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        capabilityIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetCapabilitiesOpportunityCommandSchema = {
    title: 'SetCapabilitiesOpportunityCommand',
    required: [
        'id',
        'capabilityIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        capabilityIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetHeadOfficeCompanyCommandSchema = {
    title: 'SetHeadOfficeCompanyCommand',
    required: [
        'id',
        'locationId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const SetIndustriesCompanyCommandSchema = {
    title: 'SetIndustriesCompanyCommand',
    required: [
        'id',
        'industryIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetIndustriesOpportunityCommandSchema = {
    title: 'SetIndustriesOpportunityCommand',
    required: [
        'id',
        'industryIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetServiceTypesOpportunityCommandSchema = {
    title: 'SetServiceTypesOpportunityCommand',
    required: [
        'id',
        'serviceTypeIds'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypeIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const SetStateCapabilityCommandSchema = {
    title: 'SetStateCapabilityCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateCompanyCommandSchema = {
    title: 'SetStateCompanyCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateCountryCommandSchema = {
    title: 'SetStateCountryCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateIndustryCommandSchema = {
    title: 'SetStateIndustryCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateOpportunityCommandSchema = {
    title: 'SetStateOpportunityCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateOpportunityTypeCommandSchema = {
    title: 'SetStateOpportunityTypeCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateRegionCommandSchema = {
    title: 'SetStateRegionCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStateServiceTypeCommandSchema = {
    title: 'SetStateServiceTypeCommand',
    required: [
        'id',
        'state'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        state: {
            $ref: '#/components/schemas/EntityState'
        }
    }
} as const;

export const SetStatusOpportunityCommandSchema = {
    title: 'SetStatusOpportunityCommand',
    required: [
        'id',
        'statusOpportunityStatus'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        statusOpportunityStatus: {
            $ref: '#/components/schemas/OpportunityStatus'
        }
    }
} as const;

export const SetSubmittedQuarterlyCommandSchema = {
    title: 'SetSubmittedQuarterlyCommand',
    required: [
        'id',
        'isSubmitted'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        isSubmitted: {
            type: 'boolean'
        }
    }
} as const;

export const TokenResultDtoSchema = {
    title: 'TokenResultDto',
    type: 'object',
    properties: {
        tokenType: {
            type: 'string',
            nullable: true
        },
        authenticationToken: {
            type: 'string',
            nullable: true
        },
        expiresIn: {
            type: 'integer',
            format: 'int32'
        },
        refreshToken: {
            type: 'string',
            nullable: true
        },
        userId: {
            type: 'string',
            nullable: true
        },
        userName: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCapabilityCommandSchema = {
    title: 'UpdateCapabilityCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateCompanyCommandSchema = {
    title: 'UpdateCompanyCommand',
    required: [
        'id',
        'name',
        'shortDescription',
        'fullDescription',
        'websiteUrl',
        'employeeCount',
        'serviceTypeId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        },
        employeeCount: {
            type: 'integer',
            format: 'int32'
        },
        serviceTypeId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const UpdateContactCompanyCommandSchema = {
    title: 'UpdateContactCompanyCommand',
    required: [
        'id',
        'contactId',
        'firstName',
        'lastName',
        'emailAddress',
        'companyPosition'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        contactId: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        emailAddress: {
            type: 'string',
            nullable: true
        },
        companyPosition: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateCountryCommandSchema = {
    title: 'UpdateCountryCommand',
    required: [
        'id',
        'regionId',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        regionId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateFullOpportunityCommandSchema = {
    title: 'UpdateFullOpportunityCommand',
    required: [
        'id',
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId',
        'serviceTypes',
        'capabilities',
        'industries'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        serviceTypes: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        capabilities: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        industries: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        }
    }
} as const;

export const UpdateIndustryCommandSchema = {
    title: 'UpdateIndustryCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateInfoDtoSchema = {
    title: 'UpdateInfoDto',
    type: 'object',
    properties: {
        newEmail: {
            type: 'string',
            nullable: true
        },
        newPassword: {
            type: 'string',
            nullable: true
        },
        oldPassword: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UpdateInviteCommandSchema = {
    title: 'UpdateInviteCommand',
    required: [
        'id',
        'email'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const UpdateLocationCompanyCommandSchema = {
    title: 'UpdateLocationCompanyCommand',
    required: [
        'id',
        'locationId',
        'name',
        'regionId',
        'countryId',
        'isHeadOffice'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        locationId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        regionId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        },
        isHeadOffice: {
            type: 'boolean'
        }
    }
} as const;

export const UpdateMessageOpportunityCommandSchema = {
    title: 'UpdateMessageOpportunityCommand',
    required: [
        'id',
        'messageId',
        'content'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        messageId: {
            type: 'string',
            format: 'uuid'
        },
        content: {
            type: 'string'
        }
    }
} as const;

export const UpdateOpportunityCommandSchema = {
    title: 'UpdateOpportunityCommand',
    required: [
        'id',
        'title',
        'shortDescription',
        'fullDescription',
        'deadline',
        'opportunityTypeId',
        'countryId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        shortDescription: {
            type: 'string'
        },
        fullDescription: {
            type: 'string'
        },
        deadline: {
            type: 'string',
            format: 'date',
            nullable: true
        },
        opportunityTypeId: {
            type: 'string',
            format: 'uuid'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const UpdateOpportunityTypeCommandSchema = {
    title: 'UpdateOpportunityTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateQuarterlyCommandSchema = {
    title: 'UpdateQuarterlyCommand',
    required: [
        'id',
        'year',
        'quarter',
        'isSubmitted'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        year: {
            type: 'integer',
            format: 'int32'
        },
        quarter: {
            $ref: '#/components/schemas/ReportQuarter'
        },
        isSubmitted: {
            type: 'boolean'
        }
    }
} as const;

export const UpdateRegionCommandSchema = {
    title: 'UpdateRegionCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UpdateReporPartnerQuarterlyCommandSchema = {
    title: 'UpdateReporPartnerQuarterlyCommand',
    required: [
        'id',
        'reportPartnerId',
        'name',
        'status'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        reportPartnerId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/PartnerStatus'
        }
    }
} as const;

export const UpdateReportLineQuarterlyCommandSchema = {
    title: 'UpdateReportLineQuarterlyCommand',
    required: [
        'id',
        'reprotLineId',
        'partnerCount',
        'headcount',
        'clientCount',
        'officeCount',
        'lawyerCount',
        'estimatedRevenue',
        'countryId'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        reprotLineId: {
            type: 'string',
            format: 'uuid'
        },
        partnerCount: {
            type: 'integer',
            format: 'int32'
        },
        headcount: {
            type: 'integer',
            format: 'int32'
        },
        clientCount: {
            type: 'integer',
            format: 'int32'
        },
        officeCount: {
            type: 'integer',
            format: 'int32'
        },
        lawyerCount: {
            type: 'integer',
            format: 'int32'
        },
        estimatedRevenue: {
            type: 'number',
            format: 'double'
        },
        countryId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const UpdateReviewCommandSchema = {
    title: 'UpdateReviewCommand',
    required: [
        'id',
        'comment',
        'rating'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        comment: {
            type: 'string'
        },
        rating: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UpdateServiceTypeCommandSchema = {
    title: 'UpdateServiceTypeCommand',
    required: [
        'id',
        'name',
        'description'
    ],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const UserCompanyDtoSchema = {
    title: 'UserCompanyDto',
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        websiteUrl: {
            type: 'string'
        }
    }
} as const;

export const UserDetailDtoSchema = {
    title: 'UserDetailDto',
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        companyId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        companyName: {
            type: 'string',
            nullable: true
        },
        companies: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/UserCompanyDto'
            }
        }
    }
} as const;
