// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiCompanyProfilesByIdData, DeleteApiCompanyProfilesByIdErrors, DeleteApiCompanyProfilesByIdResponses, DeleteApiIndustriesByIdData, DeleteApiIndustriesByIdErrors, DeleteApiIndustriesByIdResponses, GetApiAccountManageInfoData, GetApiAccountManageInfoResponses, GetApiCompanyProfilesByIdData, GetApiCompanyProfilesByIdErrors, GetApiCompanyProfilesByIdResponses, GetApiCompanyProfilesCompanyCountData, GetApiCompanyProfilesCompanyCountErrors, GetApiCompanyProfilesCompanyCountResponses, GetApiCompanyProfilesData, GetApiCompanyProfilesErrors, GetApiCompanyProfilesGetCompanyNamesData, GetApiCompanyProfilesGetCompanyNamesErrors, GetApiCompanyProfilesGetCompanyNamesResponses, GetApiCompanyProfilesResponses, GetApiIndustriesByIdData, GetApiIndustriesByIdErrors, GetApiIndustriesByIdResponses, GetApiIndustriesData, GetApiIndustriesErrors, GetApiIndustriesResponses, PostApiAccountConfirmEmailData, PostApiAccountConfirmEmailResponses, PostApiAccountForgotPasswordData, PostApiAccountForgotPasswordResponses, PostApiAccountLoginData, PostApiAccountLoginResponses, PostApiAccountLogoutData, PostApiAccountLogoutResponses, PostApiAccountManageInfoData, PostApiAccountManageInfoResponses, PostApiAccountRefreshData, PostApiAccountRefreshResponses, PostApiAccountRegisterData, PostApiAccountRegisterResponses, PostApiAccountResetPasswordData, PostApiAccountResetPasswordResponses, PostApiCompanyProfilesData, PostApiCompanyProfilesErrors, PostApiCompanyProfilesResponses, PostApiIndustriesData, PostApiIndustriesErrors, PostApiIndustriesResponses, PutApiCompanyProfilesByIdProfileData, PutApiCompanyProfilesByIdProfileErrors, PutApiCompanyProfilesByIdProfileResponses, PutApiIndustriesByIdData, PutApiIndustriesByIdErrors, PutApiIndustriesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAccountRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountRegisterData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountRegisterResponses, unknown, ThrowOnError>({
    url: '/api/Account/Register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountLoginResponses, unknown, ThrowOnError>({
    url: '/api/Account/Login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountRefresh = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountRefreshData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountRefreshResponses, unknown, ThrowOnError>({
    url: '/api/Account/Refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountConfirmEmail = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountConfirmEmailData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountConfirmEmailResponses, unknown, ThrowOnError>({
    url: '/api/Account/ConfirmEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountForgotPassword = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountForgotPasswordData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountForgotPasswordResponses, unknown, ThrowOnError>({
    url: '/api/Account/forgotPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountResetPassword = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountResetPasswordData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountResetPasswordResponses, unknown, ThrowOnError>({
    url: '/api/Account/resetPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiAccountManageInfo = <ThrowOnError extends boolean = false>(options?: Options<GetApiAccountManageInfoData, ThrowOnError>) => (options?.client ?? client).get<GetApiAccountManageInfoResponses, unknown, ThrowOnError>({ url: '/api/Account/manage/info', ...options });

export const postApiAccountManageInfo = <ThrowOnError extends boolean = false>(options: Options<PostApiAccountManageInfoData, ThrowOnError>) => (options.client ?? client).post<PostApiAccountManageInfoResponses, unknown, ThrowOnError>({
    url: '/api/Account/manage/info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiAccountLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiAccountLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostApiAccountLogoutResponses, unknown, ThrowOnError>({ url: '/api/Account/Logout', ...options });

export const getApiCompanyProfiles = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompanyProfilesData, ThrowOnError>) => (options?.client ?? client).get<GetApiCompanyProfilesResponses, GetApiCompanyProfilesErrors, ThrowOnError>({ url: '/api/company-profiles', ...options });

export const postApiCompanyProfiles = <ThrowOnError extends boolean = false>(options: Options<PostApiCompanyProfilesData, ThrowOnError>) => (options.client ?? client).post<PostApiCompanyProfilesResponses, PostApiCompanyProfilesErrors, ThrowOnError>({
    url: '/api/company-profiles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiCompanyProfilesById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiCompanyProfilesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiCompanyProfilesByIdResponses, DeleteApiCompanyProfilesByIdErrors, ThrowOnError>({ url: '/api/company-profiles/{id}', ...options });

export const getApiCompanyProfilesById = <ThrowOnError extends boolean = false>(options: Options<GetApiCompanyProfilesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiCompanyProfilesByIdResponses, GetApiCompanyProfilesByIdErrors, ThrowOnError>({ url: '/api/company-profiles/{id}', ...options });

export const putApiCompanyProfilesByIdProfile = <ThrowOnError extends boolean = false>(options: Options<PutApiCompanyProfilesByIdProfileData, ThrowOnError>) => (options.client ?? client).put<PutApiCompanyProfilesByIdProfileResponses, PutApiCompanyProfilesByIdProfileErrors, ThrowOnError>({
    url: '/api/company-profiles/{id}/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiCompanyProfilesCompanyCount = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompanyProfilesCompanyCountData, ThrowOnError>) => (options?.client ?? client).get<GetApiCompanyProfilesCompanyCountResponses, GetApiCompanyProfilesCompanyCountErrors, ThrowOnError>({ url: '/api/company-profiles/company-count', ...options });

export const getApiCompanyProfilesGetCompanyNames = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompanyProfilesGetCompanyNamesData, ThrowOnError>) => (options?.client ?? client).get<GetApiCompanyProfilesGetCompanyNamesResponses, GetApiCompanyProfilesGetCompanyNamesErrors, ThrowOnError>({ url: '/api/company-profiles/get-company-names', ...options });

export const getApiIndustries = <ThrowOnError extends boolean = false>(options?: Options<GetApiIndustriesData, ThrowOnError>) => (options?.client ?? client).get<GetApiIndustriesResponses, GetApiIndustriesErrors, ThrowOnError>({ url: '/api/industries', ...options });

export const postApiIndustries = <ThrowOnError extends boolean = false>(options: Options<PostApiIndustriesData, ThrowOnError>) => (options.client ?? client).post<PostApiIndustriesResponses, PostApiIndustriesErrors, ThrowOnError>({
    url: '/api/industries',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiIndustriesById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiIndustriesByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiIndustriesByIdResponses, DeleteApiIndustriesByIdErrors, ThrowOnError>({ url: '/api/industries/{id}', ...options });

export const getApiIndustriesById = <ThrowOnError extends boolean = false>(options: Options<GetApiIndustriesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiIndustriesByIdResponses, GetApiIndustriesByIdErrors, ThrowOnError>({ url: '/api/industries/{id}', ...options });

export const putApiIndustriesById = <ThrowOnError extends boolean = false>(options: Options<PutApiIndustriesByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiIndustriesByIdResponses, PutApiIndustriesByIdErrors, ThrowOnError>({
    url: '/api/industries/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
