// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiCompaniesByIdPartnerResponse, GetApiOppertunitiesByIdResponse, GetApiOppertunitiesResponse } from './types.gen';

const partnerOppertunityDtoSchemaResponseTransformer = (data: any) => {
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

const partnerProfileSchemaResponseTransformer = (data: any) => {
    if (data.oppertunities) {
        data.oppertunities = data.oppertunities.map((item: any) => partnerOppertunityDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiCompaniesByIdPartnerResponseTransformer = async (data: any): Promise<GetApiCompaniesByIdPartnerResponse> => {
    data = partnerProfileSchemaResponseTransformer(data);
    return data;
};

const oppertunityListItemDtoSchemaResponseTransformer = (data: any) => {
    if (data.createdDate) {
        data.createdDate = new Date(data.createdDate);
    }
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

export const getApiOppertunitiesResponseTransformer = async (data: any): Promise<GetApiOppertunitiesResponse> => {
    data = data.map((item: any) => oppertunityListItemDtoSchemaResponseTransformer(item));
    return data;
};

const oppertunityDtoSchemaResponseTransformer = (data: any) => {
    if (data.createdDate) {
        data.createdDate = new Date(data.createdDate);
    }
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

export const getApiOppertunitiesByIdResponseTransformer = async (data: any): Promise<GetApiOppertunitiesByIdResponse> => {
    data = oppertunityDtoSchemaResponseTransformer(data);
    return data;
};
