// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiCompaniesByIdPartnerResponse, GetApiOpportunitiesByIdResponse, GetApiOpportunitiesMeResponse, GetApiOpportunitiesResponse, GetApiOpportunitiesSavedResponse } from './types.gen';

const partnerOpportunityDtoSchemaResponseTransformer = (data: any) => {
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

const partnerProfileSchemaResponseTransformer = (data: any) => {
    if (data.opportunities) {
        data.opportunities = data.opportunities.map((item: any) => partnerOpportunityDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const getApiCompaniesByIdPartnerResponseTransformer = async (data: any): Promise<GetApiCompaniesByIdPartnerResponse> => {
    data = partnerProfileSchemaResponseTransformer(data);
    return data;
};

const opportunityListItemDtoSchemaResponseTransformer = (data: any) => {
    if (data.createdDate) {
        data.createdDate = new Date(data.createdDate);
    }
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

export const getApiOpportunitiesResponseTransformer = async (data: any): Promise<GetApiOpportunitiesResponse> => {
    data = data.map((item: any) => opportunityListItemDtoSchemaResponseTransformer(item));
    return data;
};

const opportunityDtoSchemaResponseTransformer = (data: any) => {
    if (data.createdDate) {
        data.createdDate = new Date(data.createdDate);
    }
    if (data.deadline) {
        data.deadline = new Date(data.deadline);
    }
    return data;
};

export const getApiOpportunitiesByIdResponseTransformer = async (data: any): Promise<GetApiOpportunitiesByIdResponse> => {
    data = opportunityDtoSchemaResponseTransformer(data);
    return data;
};

export const getApiOpportunitiesMeResponseTransformer = async (data: any): Promise<GetApiOpportunitiesMeResponse> => {
    data = data.map((item: any) => opportunityListItemDtoSchemaResponseTransformer(item));
    return data;
};

export const getApiOpportunitiesSavedResponseTransformer = async (data: any): Promise<GetApiOpportunitiesSavedResponse> => {
    data = data.map((item: any) => opportunityListItemDtoSchemaResponseTransformer(item));
    return data;
};
