// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://AndersonAPI.Api.json` | (string & {});
};

/**
 * AddContactCompanyCommand
 */
export type AddContactCompanyCommand = {
    id: string;
    firstName: string;
    lastName: string;
    emailAddress: string | null;
    companyPosition: string | null;
};

/**
 * AddLocationCompanyCommand
 */
export type AddLocationCompanyCommand = {
    id: string;
    name: string;
    regionId: string;
    countryId: string;
    isHeadOffice: boolean;
};

/**
 * AddMessageOpportunityCommand
 */
export type AddMessageOpportunityCommand = {
    opportunityId: string;
    content: string;
    createdDate: Date;
    createdByUser: string;
    createdByPartner: string | null;
};

/**
 * AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Guid
 */
export type AndersonApiApiControllersResponseTypesJsonResponseOfGuid = {
    value: string;
};

/**
 * CapabilityDto
 */
export type CapabilityDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
};

/**
 * CompanyApplicationIdentityUserDto
 */
export type CompanyApplicationIdentityUserDto = {
    [key: string]: unknown;
};

/**
 * CompanyCapabilityDto
 */
export type CompanyCapabilityDto = {
    id?: string;
    name?: string;
};

/**
 * CompanyContactDto
 */
export type CompanyContactDto = {
    id?: string;
    firstName?: string;
    lastName?: string;
    emailAddress?: string | null;
    companyPosition?: string | null;
    order?: number;
};

/**
 * CompanyDto
 */
export type CompanyDto = {
    name?: string;
    shortDescription?: string;
    fullDescription?: string;
    websiteUrl?: string;
    employeeCount?: number;
    id?: string;
    order?: number;
};

/**
 * CompanyIndustryDto
 */
export type CompanyIndustryDto = {
    id?: string;
    name?: string;
};

/**
 * CompanyInviteDto
 */
export type CompanyInviteDto = {
    id?: string;
    name?: string;
    email?: string;
};

/**
 * CompanyLocationDto
 */
export type CompanyLocationDto = {
    id?: string;
    name?: string;
    isHeadOffice?: boolean;
    regionId?: string;
    countryId?: string;
    order?: number;
};

/**
 * CompanyProfileDto
 */
export type CompanyProfileDto = {
    id?: string;
    name?: string;
    shortDescription?: string;
    fullDescription?: string;
    websiteUrl?: string;
    employeeCount?: number;
    applicationIdentityUsers?: Array<CompanyApplicationIdentityUserDto>;
    capabilities?: Array<CompanyCapabilityDto>;
    serviceTypes?: Array<CompanyServiceTypeDto>;
    industries?: Array<CompanyIndustryDto>;
    contacts?: Array<CompanyContactDto>;
    locations?: Array<CompanyLocationDto>;
    invites?: Array<CompanyInviteDto>;
    state?: EntityState;
};

/**
 * CompanyServiceTypeDto
 */
export type CompanyServiceTypeDto = {
    id?: string;
    name?: string;
    description?: string;
    order?: number;
    state?: EntityState;
};

/**
 * ConfirmEmailDto
 */
export type ConfirmEmailDto = {
    userId?: string | null;
    code?: string | null;
};

/**
 * CountryDto
 */
export type CountryDto = {
    regionId?: string | null;
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * CreateCapabilityCommand
 */
export type CreateCapabilityCommand = {
    name: string;
    description: string;
};

/**
 * CreateCompanyCommand
 */
export type CreateCompanyCommand = {
    name: string;
    shortDescription: string;
    fullDescription: string;
    websiteUrl: string;
    employeeCount: number;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    industries: Array<string>;
};

/**
 * CreateCountryCommand
 */
export type CreateCountryCommand = {
    regionId: string | null;
    name: string;
    description: string;
};

/**
 * CreateIndustryCommand
 */
export type CreateIndustryCommand = {
    name: string;
    description: string;
};

/**
 * CreateOpportunityCommand
 */
export type CreateOpportunityCommand = {
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    opportunityTypeId: string;
    countryId: string;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    companyId: string;
    industries: Array<string>;
};

/**
 * CreateOpportunityTypeCommand
 */
export type CreateOpportunityTypeCommand = {
    name: string;
    description: string;
};

/**
 * CreateRegionCommand
 */
export type CreateRegionCommand = {
    name: string;
    description: string;
};

/**
 * CreateReviewCommand
 */
export type CreateReviewCommand = {
    comment: string;
    rating: number;
    applicationIdentityUserId: string;
    reviewerCompanyId: string;
    state: EntityState;
};

/**
 * CreateServiceTypeCommand
 */
export type CreateServiceTypeCommand = {
    name: string;
    description: string;
};

/**
 * DirectoryProfileListItem
 */
export type DirectoryProfileListItem = {
    id?: string;
    name?: string;
    shortDescription?: string;
    capabilities?: Array<PartnerCapabilityDto>;
    locations?: Array<PartnerLocationDto>;
    contacts?: Array<PartnerContactDto>;
    industries?: Array<PartnerIndustryDto>;
    serviceTypes?: Array<PartnerServiceTypeDto>;
};

export type EntityState = number;

/**
 * ForgotPasswordDto
 */
export type ForgotPasswordDto = {
    email?: string | null;
};

/**
 * GetPartnersByAIQuery
 */
export type GetPartnersByAiQuery = {
    query: string;
};

/**
 * IndustryDto
 */
export type IndustryDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
};

/**
 * InfoResponseDto
 */
export type InfoResponseDto = {
    email?: string | null;
};

/**
 * InterestedPartnerDto
 */
export type InterestedPartnerDto = {
    id?: string;
    name?: string;
    websiteUrl?: string;
};

/**
 * LoginDto
 */
export type LoginDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * OpportunityCapabilityDto
 */
export type OpportunityCapabilityDto = {
    id?: string;
    name?: string;
};

/**
 * OpportunityDto
 */
export type OpportunityDto = {
    title?: string;
    fullDescription?: string;
    createdDate?: Date;
    deadline?: Date | null;
    companyId?: string;
    id?: string;
    country?: string;
    opportunityType?: string;
    capabilities?: Array<OpportunityCapabilityDto>;
    industries?: Array<OpportunityIndustryDto>;
    serviceTypes?: Array<OpportunityServiceTypeDto>;
    status?: OpportunityStatus;
    shortDescription?: string;
    opportunityTypeId?: string;
    countryId?: string;
};

/**
 * OpportunityIndustryDto
 */
export type OpportunityIndustryDto = {
    id?: string;
    name?: string;
};

/**
 * OpportunityListItemDto
 */
export type OpportunityListItemDto = {
    title?: string;
    shortDescription?: string;
    createdDate?: Date;
    deadline?: Date | null;
    companyId?: string;
    companyName?: string;
    id?: string;
    order?: number;
    country?: string;
    opportunityTypeString?: string;
    interestedPartners?: Array<InterestedPartnerDto>;
    capabilities?: Array<OpportunityCapabilityDto>;
};

/**
 * OpportunityServiceTypeDto
 */
export type OpportunityServiceTypeDto = {
    id?: string;
    name?: string;
};

export type OpportunityStatus = number;

/**
 * OpportunityTypeDto
 */
export type OpportunityTypeDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * PartnerCapabilityDto
 */
export type PartnerCapabilityDto = {
    id?: string;
    name?: string;
};

/**
 * PartnerContactDto
 */
export type PartnerContactDto = {
    id?: string;
    firstName?: string;
    lastName?: string;
    emailAddress?: string | null;
    companyPosition?: string | null;
};

/**
 * PartnerIndustryDto
 */
export type PartnerIndustryDto = {
    id?: string;
    name?: string;
};

/**
 * PartnerLocationDto
 */
export type PartnerLocationDto = {
    id?: string;
    name?: string;
    isHeadOffice?: boolean;
    countryId?: string;
    country?: string;
    regionId?: string;
    region?: string;
};

/**
 * PartnerOpportunityDto
 */
export type PartnerOpportunityDto = {
    id?: string;
    title?: string;
    shortDescription?: string;
    serviceTypes?: Array<unknown>;
    country?: string;
    deadline?: Date | null;
    status?: OpportunityStatus;
    companyId?: string;
    opportunityType?: string;
};

/**
 * PartnerProfile
 */
export type PartnerProfile = {
    id?: string;
    name?: string;
    fullDescription?: string;
    websiteUrl?: string;
    capabilities?: Array<PartnerCapabilityDto>;
    contacts?: Array<PartnerContactDto>;
    industries?: Array<PartnerIndustryDto>;
    locations?: Array<PartnerLocationDto>;
    serviceTypes?: Array<PartnerServiceTypeDto>;
    opportunities?: Array<PartnerOpportunityDto>;
    reviews?: Array<PartnerReviewDto>;
};

/**
 * PartnerProfileListItem
 */
export type PartnerProfileListItem = {
    id?: string;
    name?: string;
    shortDescription?: string;
    capabilities?: Array<PartnerCapabilityDto>;
    locations?: Array<PartnerLocationDto>;
    contacts?: Array<PartnerContactDto>;
    matchScore?: number;
};

/**
 * PartnerReviewDto
 */
export type PartnerReviewDto = {
    id?: string;
    comment?: string;
    rating?: number;
    applicationIdentityUserId?: string;
    reviewerCompanyId?: string;
    order?: number;
    state?: EntityState;
};

/**
 * PartnerServiceTypeDto
 */
export type PartnerServiceTypeDto = {
    id?: string;
    name?: string;
    description?: string;
    order?: number;
    state?: EntityState;
};

/**
 * ProblemDetails
 */
export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

/**
 * RefreshTokenDto
 */
export type RefreshTokenDto = {
    refreshToken?: string | null;
};

/**
 * RegionDto
 */
export type RegionDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * RegisterDto
 */
export type RegisterDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * ResetPasswordDto
 */
export type ResetPasswordDto = {
    email?: string | null;
    resetCode?: string | null;
    newPassword?: string | null;
};

/**
 * ReviewDto
 */
export type ReviewDto = {
    comment?: string;
    rating?: number;
    applicationIdentityUserId?: string;
    reviewerCompanyId?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * ScrapeWebsiteCommand
 */
export type ScrapeWebsiteCommand = {
    url: string;
};

/**
 * ServiceTypeDto
 */
export type ServiceTypeDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * SetCapabilitiesCompanyCommand
 */
export type SetCapabilitiesCompanyCommand = {
    id: string;
    capabilityIds: Array<string>;
};

/**
 * SetCapabilitiesOpportunityCommand
 */
export type SetCapabilitiesOpportunityCommand = {
    id: string;
    capabilityIds: Array<string>;
};

/**
 * SetHeadOfficeCompanyCommand
 */
export type SetHeadOfficeCompanyCommand = {
    id: string;
    locationId: string;
};

/**
 * SetIndustriesCompanyCommand
 */
export type SetIndustriesCompanyCommand = {
    id: string;
    industryIds: Array<string>;
};

/**
 * SetIndustriesOpportunityCommand
 */
export type SetIndustriesOpportunityCommand = {
    id: string;
    industryIds: Array<string>;
};

/**
 * SetInterestedPartnersOpportunityCommand
 */
export type SetInterestedPartnersOpportunityCommand = {
    id: string;
    companyIds: Array<string>;
};

/**
 * SetServiceTypesCompanyCommand
 */
export type SetServiceTypesCompanyCommand = {
    id: string;
    serviceTypeIds: Array<string>;
};

/**
 * SetServiceTypesOpportunityCommand
 */
export type SetServiceTypesOpportunityCommand = {
    id: string;
    serviceTypeIds: Array<string>;
};

/**
 * SetStateCapabilityCommand
 */
export type SetStateCapabilityCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateCompanyCommand
 */
export type SetStateCompanyCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateCountryCommand
 */
export type SetStateCountryCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateIndustryCommand
 */
export type SetStateIndustryCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateOpportunityCommand
 */
export type SetStateOpportunityCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateOpportunityTypeCommand
 */
export type SetStateOpportunityTypeCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateRegionCommand
 */
export type SetStateRegionCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStateServiceTypeCommand
 */
export type SetStateServiceTypeCommand = {
    id: string;
    state: EntityState;
};

/**
 * SetStatusOpportunityCommand
 */
export type SetStatusOpportunityCommand = {
    id: string;
    statusOpportunityStatus: OpportunityStatus;
};

/**
 * TokenResultDto
 */
export type TokenResultDto = {
    tokenType?: string | null;
    authenticationToken?: string | null;
    expiresIn?: number;
    refreshToken?: string | null;
};

/**
 * UpdateCapabilityCommand
 */
export type UpdateCapabilityCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * UpdateCompanyCommand
 */
export type UpdateCompanyCommand = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    websiteUrl: string;
    employeeCount: number;
};

/**
 * UpdateContactCompanyCommand
 */
export type UpdateContactCompanyCommand = {
    id: string;
    contactId: string;
    firstName: string;
    lastName: string;
    emailAddress: string | null;
    companyPosition: string | null;
};

/**
 * UpdateCountryCommand
 */
export type UpdateCountryCommand = {
    id: string;
    regionId: string | null;
    name: string;
    description: string;
};

/**
 * UpdateFullOpportunityCommand
 */
export type UpdateFullOpportunityCommand = {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    opportunityTypeId: string;
    countryId: string;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    industries: Array<string>;
};

/**
 * UpdateIndustryCommand
 */
export type UpdateIndustryCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * UpdateInfoDto
 */
export type UpdateInfoDto = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

/**
 * UpdateLocationCompanyCommand
 */
export type UpdateLocationCompanyCommand = {
    id: string;
    locationId: string;
    name: string;
    regionId: string;
    countryId: string;
    isHeadOffice: boolean;
};

/**
 * UpdateMessageOpportunityCommand
 */
export type UpdateMessageOpportunityCommand = {
    id: string;
    messageId: string;
    content: string;
};

/**
 * UpdateOpportunityCommand
 */
export type UpdateOpportunityCommand = {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    opportunityTypeId: string;
    countryId: string;
};

/**
 * UpdateOpportunityTypeCommand
 */
export type UpdateOpportunityTypeCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * UpdateRegionCommand
 */
export type UpdateRegionCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * UpdateReviewCommand
 */
export type UpdateReviewCommand = {
    id: string;
    comment: string;
    rating: number;
};

/**
 * UpdateServiceTypeCommand
 */
export type UpdateServiceTypeCommand = {
    id: string;
    name: string;
    description: string;
};

export type PostApiAccountRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/Account/Register';
};

export type PostApiAccountRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/Account/Login';
};

export type PostApiAccountLoginResponses = {
    /**
     * OK
     */
    200: TokenResultDto;
};

export type PostApiAccountLoginResponse = PostApiAccountLoginResponses[keyof PostApiAccountLoginResponses];

export type PostApiAccountRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/api/Account/Refresh';
};

export type PostApiAccountRefreshResponses = {
    /**
     * OK
     */
    200: TokenResultDto;
};

export type PostApiAccountRefreshResponse = PostApiAccountRefreshResponses[keyof PostApiAccountRefreshResponses];

export type PostApiAccountConfirmEmailData = {
    body: ConfirmEmailDto;
    path?: never;
    query?: never;
    url: '/api/Account/ConfirmEmail';
};

export type PostApiAccountConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/forgotPassword';
};

export type PostApiAccountForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/resetPassword';
};

export type PostApiAccountResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAccountManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type GetApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponseDto;
};

export type GetApiAccountManageInfoResponse = GetApiAccountManageInfoResponses[keyof GetApiAccountManageInfoResponses];

export type PostApiAccountManageInfoData = {
    body: UpdateInfoDto;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type PostApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponseDto;
};

export type PostApiAccountManageInfoResponse = PostApiAccountManageInfoResponses[keyof PostApiAccountManageInfoResponses];

export type PostApiAccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/Logout';
};

export type PostApiAccountLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/capabilities';
};

export type GetApiCapabilitiesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCapabilitiesError = GetApiCapabilitiesErrors[keyof GetApiCapabilitiesErrors];

export type GetApiCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<CapabilityDto>;
};

export type GetApiCapabilitiesResponse = GetApiCapabilitiesResponses[keyof GetApiCapabilitiesResponses];

export type PostApiCapabilitiesData = {
    body: CreateCapabilityCommand;
    path?: never;
    query?: never;
    url: '/api/capabilities';
};

export type PostApiCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCapabilitiesError = PostApiCapabilitiesErrors[keyof PostApiCapabilitiesErrors];

export type PostApiCapabilitiesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiCapabilitiesResponse = PostApiCapabilitiesResponses[keyof PostApiCapabilitiesResponses];

export type DeleteApiCapabilitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type DeleteApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCapabilitiesByIdError = DeleteApiCapabilitiesByIdErrors[keyof DeleteApiCapabilitiesByIdErrors];

export type DeleteApiCapabilitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCapabilitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type GetApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCapabilitiesByIdError = GetApiCapabilitiesByIdErrors[keyof GetApiCapabilitiesByIdErrors];

export type GetApiCapabilitiesByIdResponses = {
    /**
     * OK
     */
    200: CapabilityDto;
};

export type GetApiCapabilitiesByIdResponse = GetApiCapabilitiesByIdResponses[keyof GetApiCapabilitiesByIdResponses];

export type PutApiCapabilitiesByIdData = {
    body: UpdateCapabilityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type PutApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCapabilitiesByIdError = PutApiCapabilitiesByIdErrors[keyof PutApiCapabilitiesByIdErrors];

export type PutApiCapabilitiesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCapabilitiesByIdResponse = PutApiCapabilitiesByIdResponses[keyof PutApiCapabilitiesByIdResponses];

export type PutApiCapabilitiesByIdSetStateData = {
    body: SetStateCapabilityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}/set-state';
};

export type PutApiCapabilitiesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCapabilitiesByIdSetStateError = PutApiCapabilitiesByIdSetStateErrors[keyof PutApiCapabilitiesByIdSetStateErrors];

export type PutApiCapabilitiesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCapabilitiesByIdSetStateResponse = PutApiCapabilitiesByIdSetStateResponses[keyof PutApiCapabilitiesByIdSetStateResponses];

export type DeleteApiCompaniesByIdContactData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        contactId: string;
    };
    url: '/api/companies/{id}/contact';
};

export type DeleteApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCompaniesByIdContactError = DeleteApiCompaniesByIdContactErrors[keyof DeleteApiCompaniesByIdContactErrors];

export type DeleteApiCompaniesByIdContactResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCompaniesByIdContactData = {
    body: AddContactCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/contact';
};

export type PostApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCompaniesByIdContactError = PostApiCompaniesByIdContactErrors[keyof PostApiCompaniesByIdContactErrors];

export type PostApiCompaniesByIdContactResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PutApiCompaniesByIdContactData = {
    body: UpdateContactCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/contact';
};

export type PutApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdContactError = PutApiCompaniesByIdContactErrors[keyof PutApiCompaniesByIdContactErrors];

export type PutApiCompaniesByIdContactResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdContactResponse = PutApiCompaniesByIdContactResponses[keyof PutApiCompaniesByIdContactResponses];

export type DeleteApiCompaniesByIdLocationData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        locationId: string;
    };
    url: '/api/companies/{id}/location';
};

export type DeleteApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCompaniesByIdLocationError = DeleteApiCompaniesByIdLocationErrors[keyof DeleteApiCompaniesByIdLocationErrors];

export type DeleteApiCompaniesByIdLocationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCompaniesByIdLocationData = {
    body: AddLocationCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/location';
};

export type PostApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCompaniesByIdLocationError = PostApiCompaniesByIdLocationErrors[keyof PostApiCompaniesByIdLocationErrors];

export type PostApiCompaniesByIdLocationResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PutApiCompaniesByIdLocationData = {
    body: UpdateLocationCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/location';
};

export type PutApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdLocationError = PutApiCompaniesByIdLocationErrors[keyof PutApiCompaniesByIdLocationErrors];

export type PutApiCompaniesByIdLocationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdLocationResponse = PutApiCompaniesByIdLocationResponses[keyof PutApiCompaniesByIdLocationResponses];

export type GetApiCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type GetApiCompaniesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompaniesError = GetApiCompaniesErrors[keyof GetApiCompaniesErrors];

export type GetApiCompaniesResponses = {
    /**
     * OK
     */
    200: Array<DirectoryProfileListItem>;
};

export type GetApiCompaniesResponse = GetApiCompaniesResponses[keyof GetApiCompaniesResponses];

export type PostApiCompaniesData = {
    body: CreateCompanyCommand;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type PostApiCompaniesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCompaniesError = PostApiCompaniesErrors[keyof PostApiCompaniesErrors];

export type PostApiCompaniesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiCompaniesResponse = PostApiCompaniesResponses[keyof PostApiCompaniesResponses];

export type DeleteApiCompaniesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type DeleteApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCompaniesByIdError = DeleteApiCompaniesByIdErrors[keyof DeleteApiCompaniesByIdErrors];

export type DeleteApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCompaniesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type GetApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompaniesByIdError = GetApiCompaniesByIdErrors[keyof GetApiCompaniesByIdErrors];

export type GetApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: CompanyDto;
};

export type GetApiCompaniesByIdResponse = GetApiCompaniesByIdResponses[keyof GetApiCompaniesByIdResponses];

export type PutApiCompaniesByIdData = {
    body: UpdateCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type PutApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdError = PutApiCompaniesByIdErrors[keyof PutApiCompaniesByIdErrors];

export type PutApiCompaniesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdResponse = PutApiCompaniesByIdResponses[keyof PutApiCompaniesByIdResponses];

export type PutApiCompaniesScrapeWebsiteData = {
    body: ScrapeWebsiteCommand;
    path?: never;
    query?: never;
    url: '/api/companies/scrape-website';
};

export type PutApiCompaniesScrapeWebsiteErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesScrapeWebsiteError = PutApiCompaniesScrapeWebsiteErrors[keyof PutApiCompaniesScrapeWebsiteErrors];

export type PutApiCompaniesScrapeWebsiteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesScrapeWebsiteResponse = PutApiCompaniesScrapeWebsiteResponses[keyof PutApiCompaniesScrapeWebsiteResponses];

export type PutApiCompaniesByIdCapabilitiesData = {
    body: SetCapabilitiesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/capabilities';
};

export type PutApiCompaniesByIdCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdCapabilitiesError = PutApiCompaniesByIdCapabilitiesErrors[keyof PutApiCompaniesByIdCapabilitiesErrors];

export type PutApiCompaniesByIdCapabilitiesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdCapabilitiesResponse = PutApiCompaniesByIdCapabilitiesResponses[keyof PutApiCompaniesByIdCapabilitiesResponses];

export type PutApiCompaniesByIdHeadOfficeData = {
    body: SetHeadOfficeCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/head-office';
};

export type PutApiCompaniesByIdHeadOfficeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdHeadOfficeError = PutApiCompaniesByIdHeadOfficeErrors[keyof PutApiCompaniesByIdHeadOfficeErrors];

export type PutApiCompaniesByIdHeadOfficeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdHeadOfficeResponse = PutApiCompaniesByIdHeadOfficeResponses[keyof PutApiCompaniesByIdHeadOfficeResponses];

export type PutApiCompaniesByIdIndustriesData = {
    body: SetIndustriesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/industries';
};

export type PutApiCompaniesByIdIndustriesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdIndustriesError = PutApiCompaniesByIdIndustriesErrors[keyof PutApiCompaniesByIdIndustriesErrors];

export type PutApiCompaniesByIdIndustriesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdIndustriesResponse = PutApiCompaniesByIdIndustriesResponses[keyof PutApiCompaniesByIdIndustriesResponses];

export type PutApiCompaniesByIdServiceTypesData = {
    body: SetServiceTypesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/service-types';
};

export type PutApiCompaniesByIdServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdServiceTypesError = PutApiCompaniesByIdServiceTypesErrors[keyof PutApiCompaniesByIdServiceTypesErrors];

export type PutApiCompaniesByIdServiceTypesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdServiceTypesResponse = PutApiCompaniesByIdServiceTypesResponses[keyof PutApiCompaniesByIdServiceTypesResponses];

export type PutApiCompaniesByIdSetStateData = {
    body: SetStateCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/set-state';
};

export type PutApiCompaniesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesByIdSetStateError = PutApiCompaniesByIdSetStateErrors[keyof PutApiCompaniesByIdSetStateErrors];

export type PutApiCompaniesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdSetStateResponse = PutApiCompaniesByIdSetStateResponses[keyof PutApiCompaniesByIdSetStateResponses];

export type GetApiCompaniesByIdProfileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/profile';
};

export type GetApiCompaniesByIdProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompaniesByIdProfileError = GetApiCompaniesByIdProfileErrors[keyof GetApiCompaniesByIdProfileErrors];

export type GetApiCompaniesByIdProfileResponses = {
    /**
     * OK
     */
    200: CompanyProfileDto;
};

export type GetApiCompaniesByIdProfileResponse = GetApiCompaniesByIdProfileResponses[keyof GetApiCompaniesByIdProfileResponses];

export type GetApiCompaniesMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies/me';
};

export type GetApiCompaniesMeErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompaniesMeError = GetApiCompaniesMeErrors[keyof GetApiCompaniesMeErrors];

export type GetApiCompaniesMeResponses = {
    /**
     * OK
     */
    200: Array<CompanyProfileDto>;
};

export type GetApiCompaniesMeResponse = GetApiCompaniesMeResponses[keyof GetApiCompaniesMeResponses];

export type GetApiCompaniesByIdPartnerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/partner';
};

export type GetApiCompaniesByIdPartnerErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompaniesByIdPartnerError = GetApiCompaniesByIdPartnerErrors[keyof GetApiCompaniesByIdPartnerErrors];

export type GetApiCompaniesByIdPartnerResponses = {
    /**
     * OK
     */
    200: PartnerProfile;
};

export type GetApiCompaniesByIdPartnerResponse = GetApiCompaniesByIdPartnerResponses[keyof GetApiCompaniesByIdPartnerResponses];

export type PutApiCompaniesPartnersData = {
    body: GetPartnersByAiQuery;
    path?: never;
    query?: never;
    url: '/api/companies/partners';
};

export type PutApiCompaniesPartnersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompaniesPartnersError = PutApiCompaniesPartnersErrors[keyof PutApiCompaniesPartnersErrors];

export type PutApiCompaniesPartnersResponses = {
    /**
     * OK
     */
    200: Array<PartnerProfileListItem>;
};

export type PutApiCompaniesPartnersResponse = PutApiCompaniesPartnersResponses[keyof PutApiCompaniesPartnersResponses];

export type GetApiCountriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/countries';
};

export type GetApiCountriesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCountriesError = GetApiCountriesErrors[keyof GetApiCountriesErrors];

export type GetApiCountriesResponses = {
    /**
     * OK
     */
    200: Array<CountryDto>;
};

export type GetApiCountriesResponse = GetApiCountriesResponses[keyof GetApiCountriesResponses];

export type PostApiCountriesData = {
    body: CreateCountryCommand;
    path?: never;
    query?: never;
    url: '/api/countries';
};

export type PostApiCountriesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCountriesError = PostApiCountriesErrors[keyof PostApiCountriesErrors];

export type PostApiCountriesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiCountriesResponse = PostApiCountriesResponses[keyof PostApiCountriesResponses];

export type DeleteApiCountriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type DeleteApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCountriesByIdError = DeleteApiCountriesByIdErrors[keyof DeleteApiCountriesByIdErrors];

export type DeleteApiCountriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCountriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type GetApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCountriesByIdError = GetApiCountriesByIdErrors[keyof GetApiCountriesByIdErrors];

export type GetApiCountriesByIdResponses = {
    /**
     * OK
     */
    200: CountryDto;
};

export type GetApiCountriesByIdResponse = GetApiCountriesByIdResponses[keyof GetApiCountriesByIdResponses];

export type PutApiCountriesByIdData = {
    body: UpdateCountryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type PutApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCountriesByIdError = PutApiCountriesByIdErrors[keyof PutApiCountriesByIdErrors];

export type PutApiCountriesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCountriesByIdResponse = PutApiCountriesByIdResponses[keyof PutApiCountriesByIdResponses];

export type PutApiCountriesByIdSetStateData = {
    body: SetStateCountryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}/set-state';
};

export type PutApiCountriesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCountriesByIdSetStateError = PutApiCountriesByIdSetStateErrors[keyof PutApiCountriesByIdSetStateErrors];

export type PutApiCountriesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCountriesByIdSetStateResponse = PutApiCountriesByIdSetStateResponses[keyof PutApiCountriesByIdSetStateResponses];

export type GetApiIndustriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type GetApiIndustriesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiIndustriesError = GetApiIndustriesErrors[keyof GetApiIndustriesErrors];

export type GetApiIndustriesResponses = {
    /**
     * OK
     */
    200: Array<IndustryDto>;
};

export type GetApiIndustriesResponse = GetApiIndustriesResponses[keyof GetApiIndustriesResponses];

export type PostApiIndustriesData = {
    body: CreateIndustryCommand;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type PostApiIndustriesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiIndustriesError = PostApiIndustriesErrors[keyof PostApiIndustriesErrors];

export type PostApiIndustriesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiIndustriesResponse = PostApiIndustriesResponses[keyof PostApiIndustriesResponses];

export type DeleteApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type DeleteApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiIndustriesByIdError = DeleteApiIndustriesByIdErrors[keyof DeleteApiIndustriesByIdErrors];

export type DeleteApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type GetApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiIndustriesByIdError = GetApiIndustriesByIdErrors[keyof GetApiIndustriesByIdErrors];

export type GetApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: IndustryDto;
};

export type GetApiIndustriesByIdResponse = GetApiIndustriesByIdResponses[keyof GetApiIndustriesByIdResponses];

export type PutApiIndustriesByIdData = {
    body: UpdateIndustryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type PutApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiIndustriesByIdError = PutApiIndustriesByIdErrors[keyof PutApiIndustriesByIdErrors];

export type PutApiIndustriesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiIndustriesByIdResponse = PutApiIndustriesByIdResponses[keyof PutApiIndustriesByIdResponses];

export type PutApiIndustriesByIdSetStateData = {
    body: SetStateIndustryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}/set-state';
};

export type PutApiIndustriesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiIndustriesByIdSetStateError = PutApiIndustriesByIdSetStateErrors[keyof PutApiIndustriesByIdSetStateErrors];

export type PutApiIndustriesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiIndustriesByIdSetStateResponse = PutApiIndustriesByIdSetStateResponses[keyof PutApiIndustriesByIdSetStateResponses];

export type PostApiOpportunitiesMessageData = {
    body: AddMessageOpportunityCommand;
    path?: never;
    query?: never;
    url: '/api/opportunities/message';
};

export type PostApiOpportunitiesMessageErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiOpportunitiesMessageError = PostApiOpportunitiesMessageErrors[keyof PostApiOpportunitiesMessageErrors];

export type PostApiOpportunitiesMessageResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetApiOpportunitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/opportunities';
};

export type GetApiOpportunitiesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunitiesError = GetApiOpportunitiesErrors[keyof GetApiOpportunitiesErrors];

export type GetApiOpportunitiesResponses = {
    /**
     * OK
     */
    200: Array<OpportunityListItemDto>;
};

export type GetApiOpportunitiesResponse = GetApiOpportunitiesResponses[keyof GetApiOpportunitiesResponses];

export type PostApiOpportunitiesData = {
    body: CreateOpportunityCommand;
    path?: never;
    query?: never;
    url: '/api/opportunities';
};

export type PostApiOpportunitiesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiOpportunitiesError = PostApiOpportunitiesErrors[keyof PostApiOpportunitiesErrors];

export type PostApiOpportunitiesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiOpportunitiesResponse = PostApiOpportunitiesResponses[keyof PostApiOpportunitiesResponses];

export type DeleteApiOpportunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}';
};

export type DeleteApiOpportunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiOpportunitiesByIdError = DeleteApiOpportunitiesByIdErrors[keyof DeleteApiOpportunitiesByIdErrors];

export type DeleteApiOpportunitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiOpportunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}';
};

export type GetApiOpportunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunitiesByIdError = GetApiOpportunitiesByIdErrors[keyof GetApiOpportunitiesByIdErrors];

export type GetApiOpportunitiesByIdResponses = {
    /**
     * OK
     */
    200: OpportunityDto;
};

export type GetApiOpportunitiesByIdResponse = GetApiOpportunitiesByIdResponses[keyof GetApiOpportunitiesByIdResponses];

export type PutApiOpportunitiesByIdData = {
    body: UpdateOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}';
};

export type PutApiOpportunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdError = PutApiOpportunitiesByIdErrors[keyof PutApiOpportunitiesByIdErrors];

export type PutApiOpportunitiesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdResponse = PutApiOpportunitiesByIdResponses[keyof PutApiOpportunitiesByIdResponses];

export type DeleteApiOpportunitiesByIdMessageData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        messageId: string;
    };
    url: '/api/opportunities/{id}/message';
};

export type DeleteApiOpportunitiesByIdMessageErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiOpportunitiesByIdMessageError = DeleteApiOpportunitiesByIdMessageErrors[keyof DeleteApiOpportunitiesByIdMessageErrors];

export type DeleteApiOpportunitiesByIdMessageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiOpportunitiesByIdMessageData = {
    body: UpdateMessageOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/message';
};

export type PutApiOpportunitiesByIdMessageErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdMessageError = PutApiOpportunitiesByIdMessageErrors[keyof PutApiOpportunitiesByIdMessageErrors];

export type PutApiOpportunitiesByIdMessageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdMessageResponse = PutApiOpportunitiesByIdMessageResponses[keyof PutApiOpportunitiesByIdMessageResponses];

export type PutApiOpportunitiesByIdCapabilitiesData = {
    body: SetCapabilitiesOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/capabilities';
};

export type PutApiOpportunitiesByIdCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdCapabilitiesError = PutApiOpportunitiesByIdCapabilitiesErrors[keyof PutApiOpportunitiesByIdCapabilitiesErrors];

export type PutApiOpportunitiesByIdCapabilitiesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdCapabilitiesResponse = PutApiOpportunitiesByIdCapabilitiesResponses[keyof PutApiOpportunitiesByIdCapabilitiesResponses];

export type PutApiOpportunitiesByIdIndustriesData = {
    body: SetIndustriesOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/industries';
};

export type PutApiOpportunitiesByIdIndustriesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdIndustriesError = PutApiOpportunitiesByIdIndustriesErrors[keyof PutApiOpportunitiesByIdIndustriesErrors];

export type PutApiOpportunitiesByIdIndustriesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdIndustriesResponse = PutApiOpportunitiesByIdIndustriesResponses[keyof PutApiOpportunitiesByIdIndustriesResponses];

export type PutApiOpportunitiesByIdInterestedPartnersData = {
    body: SetInterestedPartnersOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/interested-partners';
};

export type PutApiOpportunitiesByIdInterestedPartnersErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdInterestedPartnersError = PutApiOpportunitiesByIdInterestedPartnersErrors[keyof PutApiOpportunitiesByIdInterestedPartnersErrors];

export type PutApiOpportunitiesByIdInterestedPartnersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdInterestedPartnersResponse = PutApiOpportunitiesByIdInterestedPartnersResponses[keyof PutApiOpportunitiesByIdInterestedPartnersResponses];

export type PutApiOpportunitiesByIdServiceTypesData = {
    body: SetServiceTypesOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/service-types';
};

export type PutApiOpportunitiesByIdServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdServiceTypesError = PutApiOpportunitiesByIdServiceTypesErrors[keyof PutApiOpportunitiesByIdServiceTypesErrors];

export type PutApiOpportunitiesByIdServiceTypesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdServiceTypesResponse = PutApiOpportunitiesByIdServiceTypesResponses[keyof PutApiOpportunitiesByIdServiceTypesResponses];

export type PutApiOpportunitiesByIdSetStateData = {
    body: SetStateOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/set-state';
};

export type PutApiOpportunitiesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdSetStateError = PutApiOpportunitiesByIdSetStateErrors[keyof PutApiOpportunitiesByIdSetStateErrors];

export type PutApiOpportunitiesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdSetStateResponse = PutApiOpportunitiesByIdSetStateResponses[keyof PutApiOpportunitiesByIdSetStateResponses];

export type PutApiOpportunitiesByIdStatusData = {
    body: SetStatusOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/status';
};

export type PutApiOpportunitiesByIdStatusErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdStatusError = PutApiOpportunitiesByIdStatusErrors[keyof PutApiOpportunitiesByIdStatusErrors];

export type PutApiOpportunitiesByIdStatusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdStatusResponse = PutApiOpportunitiesByIdStatusResponses[keyof PutApiOpportunitiesByIdStatusResponses];

export type PutApiOpportunitiesByIdFullData = {
    body: UpdateFullOpportunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunities/{id}/full';
};

export type PutApiOpportunitiesByIdFullErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunitiesByIdFullError = PutApiOpportunitiesByIdFullErrors[keyof PutApiOpportunitiesByIdFullErrors];

export type PutApiOpportunitiesByIdFullResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunitiesByIdFullResponse = PutApiOpportunitiesByIdFullResponses[keyof PutApiOpportunitiesByIdFullResponses];

export type GetApiOpportunitiesMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/opportunities/me';
};

export type GetApiOpportunitiesMeErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunitiesMeError = GetApiOpportunitiesMeErrors[keyof GetApiOpportunitiesMeErrors];

export type GetApiOpportunitiesMeResponses = {
    /**
     * OK
     */
    200: Array<OpportunityListItemDto>;
};

export type GetApiOpportunitiesMeResponse = GetApiOpportunitiesMeResponses[keyof GetApiOpportunitiesMeResponses];

export type GetApiOpportunitiesSavedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/opportunities/saved';
};

export type GetApiOpportunitiesSavedErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunitiesSavedError = GetApiOpportunitiesSavedErrors[keyof GetApiOpportunitiesSavedErrors];

export type GetApiOpportunitiesSavedResponses = {
    /**
     * OK
     */
    200: Array<OpportunityListItemDto>;
};

export type GetApiOpportunitiesSavedResponse = GetApiOpportunitiesSavedResponses[keyof GetApiOpportunitiesSavedResponses];

export type GetApiOpportunityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/opportunity-types';
};

export type GetApiOpportunityTypesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunityTypesError = GetApiOpportunityTypesErrors[keyof GetApiOpportunityTypesErrors];

export type GetApiOpportunityTypesResponses = {
    /**
     * OK
     */
    200: Array<OpportunityTypeDto>;
};

export type GetApiOpportunityTypesResponse = GetApiOpportunityTypesResponses[keyof GetApiOpportunityTypesResponses];

export type PostApiOpportunityTypesData = {
    body: CreateOpportunityTypeCommand;
    path?: never;
    query?: never;
    url: '/api/opportunity-types';
};

export type PostApiOpportunityTypesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiOpportunityTypesError = PostApiOpportunityTypesErrors[keyof PostApiOpportunityTypesErrors];

export type PostApiOpportunityTypesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiOpportunityTypesResponse = PostApiOpportunityTypesResponses[keyof PostApiOpportunityTypesResponses];

export type DeleteApiOpportunityTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunity-types/{id}';
};

export type DeleteApiOpportunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiOpportunityTypesByIdError = DeleteApiOpportunityTypesByIdErrors[keyof DeleteApiOpportunityTypesByIdErrors];

export type DeleteApiOpportunityTypesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiOpportunityTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunity-types/{id}';
};

export type GetApiOpportunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOpportunityTypesByIdError = GetApiOpportunityTypesByIdErrors[keyof GetApiOpportunityTypesByIdErrors];

export type GetApiOpportunityTypesByIdResponses = {
    /**
     * OK
     */
    200: OpportunityTypeDto;
};

export type GetApiOpportunityTypesByIdResponse = GetApiOpportunityTypesByIdResponses[keyof GetApiOpportunityTypesByIdResponses];

export type PutApiOpportunityTypesByIdData = {
    body: UpdateOpportunityTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunity-types/{id}';
};

export type PutApiOpportunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunityTypesByIdError = PutApiOpportunityTypesByIdErrors[keyof PutApiOpportunityTypesByIdErrors];

export type PutApiOpportunityTypesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunityTypesByIdResponse = PutApiOpportunityTypesByIdResponses[keyof PutApiOpportunityTypesByIdResponses];

export type PutApiOpportunityTypesByIdSetStateData = {
    body: SetStateOpportunityTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/opportunity-types/{id}/set-state';
};

export type PutApiOpportunityTypesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOpportunityTypesByIdSetStateError = PutApiOpportunityTypesByIdSetStateErrors[keyof PutApiOpportunityTypesByIdSetStateErrors];

export type PutApiOpportunityTypesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOpportunityTypesByIdSetStateResponse = PutApiOpportunityTypesByIdSetStateResponses[keyof PutApiOpportunityTypesByIdSetStateResponses];

export type GetApiRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/regions';
};

export type GetApiRegionsErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiRegionsError = GetApiRegionsErrors[keyof GetApiRegionsErrors];

export type GetApiRegionsResponses = {
    /**
     * OK
     */
    200: Array<RegionDto>;
};

export type GetApiRegionsResponse = GetApiRegionsResponses[keyof GetApiRegionsResponses];

export type PostApiRegionsData = {
    body: CreateRegionCommand;
    path?: never;
    query?: never;
    url: '/api/regions';
};

export type PostApiRegionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiRegionsError = PostApiRegionsErrors[keyof PostApiRegionsErrors];

export type PostApiRegionsResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiRegionsResponse = PostApiRegionsResponses[keyof PostApiRegionsResponses];

export type DeleteApiRegionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type DeleteApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiRegionsByIdError = DeleteApiRegionsByIdErrors[keyof DeleteApiRegionsByIdErrors];

export type DeleteApiRegionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRegionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type GetApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiRegionsByIdError = GetApiRegionsByIdErrors[keyof GetApiRegionsByIdErrors];

export type GetApiRegionsByIdResponses = {
    /**
     * OK
     */
    200: RegionDto;
};

export type GetApiRegionsByIdResponse = GetApiRegionsByIdResponses[keyof GetApiRegionsByIdResponses];

export type PutApiRegionsByIdData = {
    body: UpdateRegionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type PutApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiRegionsByIdError = PutApiRegionsByIdErrors[keyof PutApiRegionsByIdErrors];

export type PutApiRegionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiRegionsByIdResponse = PutApiRegionsByIdResponses[keyof PutApiRegionsByIdResponses];

export type PutApiRegionsByIdSetStateData = {
    body: SetStateRegionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}/set-state';
};

export type PutApiRegionsByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiRegionsByIdSetStateError = PutApiRegionsByIdSetStateErrors[keyof PutApiRegionsByIdSetStateErrors];

export type PutApiRegionsByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiRegionsByIdSetStateResponse = PutApiRegionsByIdSetStateResponses[keyof PutApiRegionsByIdSetStateResponses];

export type GetApiReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type GetApiReviewsErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiReviewsError = GetApiReviewsErrors[keyof GetApiReviewsErrors];

export type GetApiReviewsResponses = {
    /**
     * OK
     */
    200: Array<ReviewDto>;
};

export type GetApiReviewsResponse = GetApiReviewsResponses[keyof GetApiReviewsResponses];

export type PostApiReviewsData = {
    body: CreateReviewCommand;
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type PostApiReviewsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiReviewsError = PostApiReviewsErrors[keyof PostApiReviewsErrors];

export type PostApiReviewsResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiReviewsResponse = PostApiReviewsResponses[keyof PostApiReviewsResponses];

export type DeleteApiReviewsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type DeleteApiReviewsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiReviewsByIdError = DeleteApiReviewsByIdErrors[keyof DeleteApiReviewsByIdErrors];

export type DeleteApiReviewsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiReviewsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type GetApiReviewsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiReviewsByIdError = GetApiReviewsByIdErrors[keyof GetApiReviewsByIdErrors];

export type GetApiReviewsByIdResponses = {
    /**
     * OK
     */
    200: ReviewDto;
};

export type GetApiReviewsByIdResponse = GetApiReviewsByIdResponses[keyof GetApiReviewsByIdResponses];

export type PutApiReviewsByIdData = {
    body: UpdateReviewCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reviews/{id}';
};

export type PutApiReviewsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiReviewsByIdError = PutApiReviewsByIdErrors[keyof PutApiReviewsByIdErrors];

export type PutApiReviewsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiReviewsByIdResponse = PutApiReviewsByIdResponses[keyof PutApiReviewsByIdResponses];

export type GetApiServiceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/service-types';
};

export type GetApiServiceTypesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiServiceTypesError = GetApiServiceTypesErrors[keyof GetApiServiceTypesErrors];

export type GetApiServiceTypesResponses = {
    /**
     * OK
     */
    200: Array<ServiceTypeDto>;
};

export type GetApiServiceTypesResponse = GetApiServiceTypesResponses[keyof GetApiServiceTypesResponses];

export type PostApiServiceTypesData = {
    body: CreateServiceTypeCommand;
    path?: never;
    query?: never;
    url: '/api/service-types';
};

export type PostApiServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiServiceTypesError = PostApiServiceTypesErrors[keyof PostApiServiceTypesErrors];

export type PostApiServiceTypesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiServiceTypesResponse = PostApiServiceTypesResponses[keyof PostApiServiceTypesResponses];

export type DeleteApiServiceTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type DeleteApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiServiceTypesByIdError = DeleteApiServiceTypesByIdErrors[keyof DeleteApiServiceTypesByIdErrors];

export type DeleteApiServiceTypesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiServiceTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type GetApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiServiceTypesByIdError = GetApiServiceTypesByIdErrors[keyof GetApiServiceTypesByIdErrors];

export type GetApiServiceTypesByIdResponses = {
    /**
     * OK
     */
    200: ServiceTypeDto;
};

export type GetApiServiceTypesByIdResponse = GetApiServiceTypesByIdResponses[keyof GetApiServiceTypesByIdResponses];

export type PutApiServiceTypesByIdData = {
    body: UpdateServiceTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type PutApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiServiceTypesByIdError = PutApiServiceTypesByIdErrors[keyof PutApiServiceTypesByIdErrors];

export type PutApiServiceTypesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiServiceTypesByIdResponse = PutApiServiceTypesByIdResponses[keyof PutApiServiceTypesByIdResponses];

export type PutApiServiceTypesByIdSetStateData = {
    body: SetStateServiceTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}/set-state';
};

export type PutApiServiceTypesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiServiceTypesByIdSetStateError = PutApiServiceTypesByIdSetStateErrors[keyof PutApiServiceTypesByIdSetStateErrors];

export type PutApiServiceTypesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiServiceTypesByIdSetStateResponse = PutApiServiceTypesByIdSetStateResponses[keyof PutApiServiceTypesByIdSetStateResponses];
