// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://AndersonAPI.Api.json` | (string & {});
};

/**
 * AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Guid
 */
export type AndersonApiApiControllersResponseTypesJsonResponseOfGuid = {
    value: string;
};

/**
 * AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_Int32
 */
export type AndersonApiApiControllersResponseTypesJsonResponseOfInt32 = {
    value: number;
};

/**
 * ByteArray
 */
export type ByteArray = string | null;

/**
 * CompanyNameDto
 */
export type CompanyNameDto = {
    name?: string;
    shortDescription?: string;
    websiteUrl?: string;
};

/**
 * CompanyProfileDto
 */
export type CompanyProfileDto = {
    name?: string;
    shortDescription?: string;
    description?: string;
    websiteUrl?: string;
    employeeCount?: number;
    embedding?: ByteArray;
    id?: string;
    order?: number;
};

/**
 * ConfirmEmailDto
 */
export type ConfirmEmailDto = {
    userId?: string | null;
    code?: string | null;
};

/**
 * CreateCompanyProfileCommand
 */
export type CreateCompanyProfileCommand = {
    name: string;
    shortDescription: string;
    description: string;
    websiteUrl: string;
    employeeCount: number;
};

/**
 * CreateIndustryCommand
 */
export type CreateIndustryCommand = {
    name: string;
    description: string;
};

/**
 * ForgotPasswordDto
 */
export type ForgotPasswordDto = {
    email?: string | null;
};

/**
 * IndustryDto
 */
export type IndustryDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
};

/**
 * InfoResponseDto
 */
export type InfoResponseDto = {
    email?: string | null;
};

/**
 * LoginDto
 */
export type LoginDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * ProblemDetails
 */
export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

/**
 * RefreshTokenDto
 */
export type RefreshTokenDto = {
    refreshToken?: string | null;
};

/**
 * RegisterDto
 */
export type RegisterDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * ResetPasswordDto
 */
export type ResetPasswordDto = {
    email?: string | null;
    resetCode?: string | null;
    newPassword?: string | null;
};

/**
 * TokenResultDto
 */
export type TokenResultDto = {
    tokenType?: string | null;
    authenticationToken?: string | null;
    expiresIn?: number;
    refreshToken?: string | null;
};

/**
 * UpdateCompanyProfileCommand
 */
export type UpdateCompanyProfileCommand = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    websiteUrl: string;
    employeeCount: number;
};

/**
 * UpdateIndustryCommand
 */
export type UpdateIndustryCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * UpdateInfoDto
 */
export type UpdateInfoDto = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type PostApiAccountRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/api/Account/Register';
};

export type PostApiAccountRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/Account/Login';
};

export type PostApiAccountLoginResponses = {
    /**
     * OK
     */
    200: TokenResultDto;
};

export type PostApiAccountLoginResponse = PostApiAccountLoginResponses[keyof PostApiAccountLoginResponses];

export type PostApiAccountRefreshData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/api/Account/Refresh';
};

export type PostApiAccountRefreshResponses = {
    /**
     * OK
     */
    200: TokenResultDto;
};

export type PostApiAccountRefreshResponse = PostApiAccountRefreshResponses[keyof PostApiAccountRefreshResponses];

export type PostApiAccountConfirmEmailData = {
    body: ConfirmEmailDto;
    path?: never;
    query?: never;
    url: '/api/Account/ConfirmEmail';
};

export type PostApiAccountConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/forgotPassword';
};

export type PostApiAccountForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/resetPassword';
};

export type PostApiAccountResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAccountManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type GetApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponseDto;
};

export type GetApiAccountManageInfoResponse = GetApiAccountManageInfoResponses[keyof GetApiAccountManageInfoResponses];

export type PostApiAccountManageInfoData = {
    body: UpdateInfoDto;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type PostApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponseDto;
};

export type PostApiAccountManageInfoResponse = PostApiAccountManageInfoResponses[keyof PostApiAccountManageInfoResponses];

export type PostApiAccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/Logout';
};

export type PostApiAccountLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCompanyProfilesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/company-profiles';
};

export type GetApiCompanyProfilesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompanyProfilesError = GetApiCompanyProfilesErrors[keyof GetApiCompanyProfilesErrors];

export type GetApiCompanyProfilesResponses = {
    /**
     * OK
     */
    200: Array<CompanyProfileDto>;
};

export type GetApiCompanyProfilesResponse = GetApiCompanyProfilesResponses[keyof GetApiCompanyProfilesResponses];

export type PostApiCompanyProfilesData = {
    body: CreateCompanyProfileCommand;
    path?: never;
    query?: never;
    url: '/api/company-profiles';
};

export type PostApiCompanyProfilesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiCompanyProfilesError = PostApiCompanyProfilesErrors[keyof PostApiCompanyProfilesErrors];

export type PostApiCompanyProfilesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiCompanyProfilesResponse = PostApiCompanyProfilesResponses[keyof PostApiCompanyProfilesResponses];

export type DeleteApiCompanyProfilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/company-profiles/{id}';
};

export type DeleteApiCompanyProfilesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiCompanyProfilesByIdError = DeleteApiCompanyProfilesByIdErrors[keyof DeleteApiCompanyProfilesByIdErrors];

export type DeleteApiCompanyProfilesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCompanyProfilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/company-profiles/{id}';
};

export type GetApiCompanyProfilesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompanyProfilesByIdError = GetApiCompanyProfilesByIdErrors[keyof GetApiCompanyProfilesByIdErrors];

export type GetApiCompanyProfilesByIdResponses = {
    /**
     * OK
     */
    200: CompanyProfileDto;
};

export type GetApiCompanyProfilesByIdResponse = GetApiCompanyProfilesByIdResponses[keyof GetApiCompanyProfilesByIdResponses];

export type PutApiCompanyProfilesByIdProfileData = {
    body: UpdateCompanyProfileCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/company-profiles/{id}/profile';
};

export type PutApiCompanyProfilesByIdProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiCompanyProfilesByIdProfileError = PutApiCompanyProfilesByIdProfileErrors[keyof PutApiCompanyProfilesByIdProfileErrors];

export type PutApiCompanyProfilesByIdProfileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompanyProfilesByIdProfileResponse = PutApiCompanyProfilesByIdProfileResponses[keyof PutApiCompanyProfilesByIdProfileResponses];

export type GetApiCompanyProfilesCompanyCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/company-profiles/company-count';
};

export type GetApiCompanyProfilesCompanyCountErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompanyProfilesCompanyCountError = GetApiCompanyProfilesCompanyCountErrors[keyof GetApiCompanyProfilesCompanyCountErrors];

export type GetApiCompanyProfilesCompanyCountResponses = {
    /**
     * OK
     */
    200: AndersonApiApiControllersResponseTypesJsonResponseOfInt32;
};

export type GetApiCompanyProfilesCompanyCountResponse = GetApiCompanyProfilesCompanyCountResponses[keyof GetApiCompanyProfilesCompanyCountResponses];

export type GetApiCompanyProfilesGetCompanyNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/company-profiles/get-company-names';
};

export type GetApiCompanyProfilesGetCompanyNamesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiCompanyProfilesGetCompanyNamesError = GetApiCompanyProfilesGetCompanyNamesErrors[keyof GetApiCompanyProfilesGetCompanyNamesErrors];

export type GetApiCompanyProfilesGetCompanyNamesResponses = {
    /**
     * OK
     */
    200: Array<CompanyNameDto>;
};

export type GetApiCompanyProfilesGetCompanyNamesResponse = GetApiCompanyProfilesGetCompanyNamesResponses[keyof GetApiCompanyProfilesGetCompanyNamesResponses];

export type GetApiIndustriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type GetApiIndustriesErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiIndustriesError = GetApiIndustriesErrors[keyof GetApiIndustriesErrors];

export type GetApiIndustriesResponses = {
    /**
     * OK
     */
    200: Array<IndustryDto>;
};

export type GetApiIndustriesResponse = GetApiIndustriesResponses[keyof GetApiIndustriesResponses];

export type PostApiIndustriesData = {
    body: CreateIndustryCommand;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type PostApiIndustriesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiIndustriesError = PostApiIndustriesErrors[keyof PostApiIndustriesErrors];

export type PostApiIndustriesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfGuid;
};

export type PostApiIndustriesResponse = PostApiIndustriesResponses[keyof PostApiIndustriesResponses];

export type DeleteApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type DeleteApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiIndustriesByIdError = DeleteApiIndustriesByIdErrors[keyof DeleteApiIndustriesByIdErrors];

export type DeleteApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type GetApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiIndustriesByIdError = GetApiIndustriesByIdErrors[keyof GetApiIndustriesByIdErrors];

export type GetApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: IndustryDto;
};

export type GetApiIndustriesByIdResponse = GetApiIndustriesByIdResponses[keyof GetApiIndustriesByIdResponses];

export type PutApiIndustriesByIdData = {
    body: UpdateIndustryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type PutApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiIndustriesByIdError = PutApiIndustriesByIdErrors[keyof PutApiIndustriesByIdErrors];

export type PutApiIndustriesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiIndustriesByIdResponse = PutApiIndustriesByIdResponses[keyof PutApiIndustriesByIdResponses];
