// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://AndersonAPI.Api.json` | (string & {});
};

/**
 * AndersonAPI.Api.Controllers.ConfirmEmailDto
 */
export type AndersonApiApiControllersConfirmEmailDto = {
    userId?: string | null;
    code?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.ForgotPasswordDto
 */
export type AndersonApiApiControllersForgotPasswordDto = {
    email?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.InfoResponseDto
 */
export type AndersonApiApiControllersInfoResponseDto = {
    email?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.LoginDto
 */
export type AndersonApiApiControllersLoginDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.RefreshTokenDto
 */
export type AndersonApiApiControllersRefreshTokenDto = {
    refreshToken?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.RegisterDto
 */
export type AndersonApiApiControllersRegisterDto = {
    email?: string | null;
    password?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.ResetPasswordDto
 */
export type AndersonApiApiControllersResetPasswordDto = {
    email?: string | null;
    resetCode?: string | null;
    newPassword?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.ResponseTypes.JsonResponse_Of_System.Guid
 */
export type AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid = {
    value: string;
};

/**
 * AndersonAPI.Api.Controllers.TokenResultDto
 */
export type AndersonApiApiControllersTokenResultDto = {
    tokenType?: string | null;
    authenticationToken?: string | null;
    expiresIn?: number;
    refreshToken?: string | null;
};

/**
 * AndersonAPI.Api.Controllers.UpdateInfoDto
 */
export type AndersonApiApiControllersUpdateInfoDto = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

/**
 * AndersonAPI.Application.Capabilities.CapabilityDto
 */
export type AndersonApiApplicationCapabilitiesCapabilityDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
};

/**
 * AndersonAPI.Application.Capabilities.CreateCapability.CreateCapabilityCommand
 */
export type AndersonApiApplicationCapabilitiesCreateCapabilityCreateCapabilityCommand = {
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Capabilities.SetStateCapability.SetStateCapabilityCommand
 */
export type AndersonApiApplicationCapabilitiesSetStateCapabilitySetStateCapabilityCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Capabilities.UpdateCapability.UpdateCapabilityCommand
 */
export type AndersonApiApplicationCapabilitiesUpdateCapabilityUpdateCapabilityCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Companies.AddContactCompany.AddContactCompanyCommand
 */
export type AndersonApiApplicationCompaniesAddContactCompanyAddContactCompanyCommand = {
    id: string;
    firstName: string;
    lastName: string;
    emailAddress: string | null;
    companyPosition: string | null;
};

/**
 * AndersonAPI.Application.Companies.AddLocationCompany.AddLocationCompanyCommand
 */
export type AndersonApiApplicationCompaniesAddLocationCompanyAddLocationCompanyCommand = {
    id: string;
    name: string;
    regionId: string;
    countryId: string;
    isHeadOffice: boolean;
};

/**
 * AndersonAPI.Application.Companies.CompanyDto
 */
export type AndersonApiApplicationCompaniesCompanyDto = {
    name?: string;
    shortDescription?: string;
    fullDescription?: string;
    websiteUrl?: string;
    employeeCount?: number;
    embedding?: SystemByteArray;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * AndersonAPI.Application.Companies.CreateCompany.CreateCompanyCommand
 */
export type AndersonApiApplicationCompaniesCreateCompanyCreateCompanyCommand = {
    name: string;
    shortDescription: string;
    fullDescription: string;
    websiteUrl: string;
    employeeCount: number;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    industries: Array<string>;
};

/**
 * AndersonAPI.Application.Companies.SetCapabilitiesCompany.SetCapabilitiesCompanyCommand
 */
export type AndersonApiApplicationCompaniesSetCapabilitiesCompanySetCapabilitiesCompanyCommand = {
    id: string;
    capabilityIds: Array<string>;
};

/**
 * AndersonAPI.Application.Companies.SetHeadOfficeCompany.SetHeadOfficeCompanyCommand
 */
export type AndersonApiApplicationCompaniesSetHeadOfficeCompanySetHeadOfficeCompanyCommand = {
    id: string;
    locationId: string;
};

/**
 * AndersonAPI.Application.Companies.SetIndustriesCompany.SetIndustriesCompanyCommand
 */
export type AndersonApiApplicationCompaniesSetIndustriesCompanySetIndustriesCompanyCommand = {
    id: string;
    industryIds: Array<string>;
};

/**
 * AndersonAPI.Application.Companies.SetServiceTypesCompany.SetServiceTypesCompanyCommand
 */
export type AndersonApiApplicationCompaniesSetServiceTypesCompanySetServiceTypesCompanyCommand = {
    id: string;
    serviceTypeIds: Array<string>;
};

/**
 * AndersonAPI.Application.Companies.SetStateCompany.SetStateCompanyCommand
 */
export type AndersonApiApplicationCompaniesSetStateCompanySetStateCompanyCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Companies.UpdateCompany.UpdateCompanyCommand
 */
export type AndersonApiApplicationCompaniesUpdateCompanyUpdateCompanyCommand = {
    id: string;
    name: string;
    shortDescription: string;
    description: string;
    websiteUrl: string;
    employeeCount: number;
};

/**
 * AndersonAPI.Application.Companies.UpdateContactCompany.UpdateContactCompanyCommand
 */
export type AndersonApiApplicationCompaniesUpdateContactCompanyUpdateContactCompanyCommand = {
    id: string;
    contactId: string;
    firstName: string;
    lastName: string;
    emailAddress: string | null;
    companyPosition: string | null;
};

/**
 * AndersonAPI.Application.Companies.UpdateLocationCompany.UpdateLocationCompanyCommand
 */
export type AndersonApiApplicationCompaniesUpdateLocationCompanyUpdateLocationCompanyCommand = {
    id: string;
    locationId: string;
    name: string;
    regionId: string;
    countryId: string;
    isHeadOffice: boolean;
};

/**
 * AndersonAPI.Application.Countries.CountryDto
 */
export type AndersonApiApplicationCountriesCountryDto = {
    regionId?: string | null;
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * AndersonAPI.Application.Countries.CreateCountry.CreateCountryCommand
 */
export type AndersonApiApplicationCountriesCreateCountryCreateCountryCommand = {
    regionId: string | null;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Countries.SetStateCountry.SetStateCountryCommand
 */
export type AndersonApiApplicationCountriesSetStateCountrySetStateCountryCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Countries.UpdateCountry.UpdateCountryCommand
 */
export type AndersonApiApplicationCountriesUpdateCountryUpdateCountryCommand = {
    id: string;
    regionId: string | null;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Industries.CreateIndustry.CreateIndustryCommand
 */
export type AndersonApiApplicationIndustriesCreateIndustryCreateIndustryCommand = {
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Industries.IndustryDto
 */
export type AndersonApiApplicationIndustriesIndustryDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
};

/**
 * AndersonAPI.Application.Industries.SetStateIndustry.SetStateIndustryCommand
 */
export type AndersonApiApplicationIndustriesSetStateIndustrySetStateIndustryCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Industries.UpdateIndustry.UpdateIndustryCommand
 */
export type AndersonApiApplicationIndustriesUpdateIndustryUpdateIndustryCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Oppertunities.CreateOppertunity.CreateOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesCreateOppertunityCreateOppertunityCommand = {
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    oppertunityTypeId: string;
    countryId: string;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    companyId: string;
    industries: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.OppertunityDto
 */
export type AndersonApiApplicationOppertunitiesOppertunityDto = {
    title?: string;
    shortDescription?: string;
    fullDescription?: string;
    deadline?: Date | null;
    status?: OppertunityStatus;
    oppertunityTypeId?: string;
    countryId?: string;
    companyId?: string;
    id?: string;
    order?: number;
};

/**
 * AndersonAPI.Application.Oppertunities.SetCapabilitiesOppertunity.SetCapabilitiesOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetCapabilitiesOppertunitySetCapabilitiesOppertunityCommand = {
    id: string;
    capabilityIds: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.SetIndustriesOppertunity.SetIndustriesOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetIndustriesOppertunitySetIndustriesOppertunityCommand = {
    id: string;
    industryIds: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.SetInterestedPartnersOppertunity.SetInterestedPartnersOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetInterestedPartnersOppertunitySetInterestedPartnersOppertunityCommand = {
    id: string;
    companyIds: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.SetServiceTypesOppertunity.SetServiceTypesOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetServiceTypesOppertunitySetServiceTypesOppertunityCommand = {
    id: string;
    serviceTypeIds: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.SetStateOppertunity.SetStateOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetStateOppertunitySetStateOppertunityCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Oppertunities.SetStatusOppertunity.SetStatusOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesSetStatusOppertunitySetStatusOppertunityCommand = {
    id: string;
    status: OppertunityStatus;
};

/**
 * AndersonAPI.Application.Oppertunities.UpdateFullOppertunity.UpdateFullOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesUpdateFullOppertunityUpdateFullOppertunityCommand = {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    oppertunityTypeId: string;
    countryId: string;
    serviceTypes: Array<string>;
    capabilities: Array<string>;
    industries: Array<string>;
};

/**
 * AndersonAPI.Application.Oppertunities.UpdateOppertunity.UpdateOppertunityCommand
 */
export type AndersonApiApplicationOppertunitiesUpdateOppertunityUpdateOppertunityCommand = {
    id: string;
    title: string;
    shortDescription: string;
    fullDescription: string;
    deadline: Date | null;
    oppertunityTypeId: string;
    countryId: string;
};

/**
 * AndersonAPI.Application.OppertunityTypes.CreateOppertunityType.CreateOppertunityTypeCommand
 */
export type AndersonApiApplicationOppertunityTypesCreateOppertunityTypeCreateOppertunityTypeCommand = {
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.OppertunityTypes.OppertunityTypeDto
 */
export type AndersonApiApplicationOppertunityTypesOppertunityTypeDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * AndersonAPI.Application.OppertunityTypes.SetStateOppertunityType.SetStateOppertunityTypeCommand
 */
export type AndersonApiApplicationOppertunityTypesSetStateOppertunityTypeSetStateOppertunityTypeCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.OppertunityTypes.UpdateOppertunityType.UpdateOppertunityTypeCommand
 */
export type AndersonApiApplicationOppertunityTypesUpdateOppertunityTypeUpdateOppertunityTypeCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Regions.CreateRegion.CreateRegionCommand
 */
export type AndersonApiApplicationRegionsCreateRegionCreateRegionCommand = {
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.Regions.RegionDto
 */
export type AndersonApiApplicationRegionsRegionDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * AndersonAPI.Application.Regions.SetStateRegion.SetStateRegionCommand
 */
export type AndersonApiApplicationRegionsSetStateRegionSetStateRegionCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.Regions.UpdateRegion.UpdateRegionCommand
 */
export type AndersonApiApplicationRegionsUpdateRegionUpdateRegionCommand = {
    id: string;
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.ServiceTypes.CreateServiceType.CreateServiceTypeCommand
 */
export type AndersonApiApplicationServiceTypesCreateServiceTypeCreateServiceTypeCommand = {
    name: string;
    description: string;
};

/**
 * AndersonAPI.Application.ServiceTypes.ServiceTypeDto
 */
export type AndersonApiApplicationServiceTypesServiceTypeDto = {
    name?: string;
    description?: string;
    id?: string;
    order?: number;
    state?: EntityState;
};

/**
 * AndersonAPI.Application.ServiceTypes.SetStateServiceType.SetStateServiceTypeCommand
 */
export type AndersonApiApplicationServiceTypesSetStateServiceTypeSetStateServiceTypeCommand = {
    id: string;
    state: EntityState;
};

/**
 * AndersonAPI.Application.ServiceTypes.UpdateServiceType.UpdateServiceTypeCommand
 */
export type AndersonApiApplicationServiceTypesUpdateServiceTypeUpdateServiceTypeCommand = {
    id: string;
    name: string;
    description: string;
};

export type EntityState = number;

/**
 * Microsoft.AspNetCore.Mvc.ProblemDetails
 */
export type MicrosoftAspNetCoreMvcProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type OppertunityStatus = number;

/**
 * System.ByteArray
 */
export type SystemByteArray = string | null;

export type PostApiAccountRegisterData = {
    body: AndersonApiApiControllersRegisterDto;
    path?: never;
    query?: never;
    url: '/api/Account/Register';
};

export type PostApiAccountRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountLoginData = {
    body: AndersonApiApiControllersLoginDto;
    path?: never;
    query?: never;
    url: '/api/Account/Login';
};

export type PostApiAccountLoginResponses = {
    /**
     * OK
     */
    200: AndersonApiApiControllersTokenResultDto;
};

export type PostApiAccountLoginResponse = PostApiAccountLoginResponses[keyof PostApiAccountLoginResponses];

export type PostApiAccountRefreshData = {
    body: AndersonApiApiControllersRefreshTokenDto;
    path?: never;
    query?: never;
    url: '/api/Account/Refresh';
};

export type PostApiAccountRefreshResponses = {
    /**
     * OK
     */
    200: AndersonApiApiControllersTokenResultDto;
};

export type PostApiAccountRefreshResponse = PostApiAccountRefreshResponses[keyof PostApiAccountRefreshResponses];

export type PostApiAccountConfirmEmailData = {
    body: AndersonApiApiControllersConfirmEmailDto;
    path?: never;
    query?: never;
    url: '/api/Account/ConfirmEmail';
};

export type PostApiAccountConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountForgotPasswordData = {
    body: AndersonApiApiControllersForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/forgotPassword';
};

export type PostApiAccountForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAccountResetPasswordData = {
    body: AndersonApiApiControllersResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/Account/resetPassword';
};

export type PostApiAccountResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiAccountManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type GetApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: AndersonApiApiControllersInfoResponseDto;
};

export type GetApiAccountManageInfoResponse = GetApiAccountManageInfoResponses[keyof GetApiAccountManageInfoResponses];

export type PostApiAccountManageInfoData = {
    body: AndersonApiApiControllersUpdateInfoDto;
    path?: never;
    query?: never;
    url: '/api/Account/manage/info';
};

export type PostApiAccountManageInfoResponses = {
    /**
     * OK
     */
    200: AndersonApiApiControllersInfoResponseDto;
};

export type PostApiAccountManageInfoResponse = PostApiAccountManageInfoResponses[keyof PostApiAccountManageInfoResponses];

export type PostApiAccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Account/Logout';
};

export type PostApiAccountLogoutResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/capabilities';
};

export type GetApiCapabilitiesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCapabilitiesError = GetApiCapabilitiesErrors[keyof GetApiCapabilitiesErrors];

export type GetApiCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationCapabilitiesCapabilityDto>;
};

export type GetApiCapabilitiesResponse = GetApiCapabilitiesResponses[keyof GetApiCapabilitiesResponses];

export type PostApiCapabilitiesData = {
    body: AndersonApiApplicationCapabilitiesCreateCapabilityCreateCapabilityCommand;
    path?: never;
    query?: never;
    url: '/api/capabilities';
};

export type PostApiCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiCapabilitiesError = PostApiCapabilitiesErrors[keyof PostApiCapabilitiesErrors];

export type PostApiCapabilitiesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiCapabilitiesResponse = PostApiCapabilitiesResponses[keyof PostApiCapabilitiesResponses];

export type DeleteApiCapabilitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type DeleteApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiCapabilitiesByIdError = DeleteApiCapabilitiesByIdErrors[keyof DeleteApiCapabilitiesByIdErrors];

export type DeleteApiCapabilitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCapabilitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type GetApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCapabilitiesByIdError = GetApiCapabilitiesByIdErrors[keyof GetApiCapabilitiesByIdErrors];

export type GetApiCapabilitiesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationCapabilitiesCapabilityDto;
};

export type GetApiCapabilitiesByIdResponse = GetApiCapabilitiesByIdResponses[keyof GetApiCapabilitiesByIdResponses];

export type PutApiCapabilitiesByIdData = {
    body: AndersonApiApplicationCapabilitiesUpdateCapabilityUpdateCapabilityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}';
};

export type PutApiCapabilitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCapabilitiesByIdError = PutApiCapabilitiesByIdErrors[keyof PutApiCapabilitiesByIdErrors];

export type PutApiCapabilitiesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCapabilitiesByIdResponse = PutApiCapabilitiesByIdResponses[keyof PutApiCapabilitiesByIdResponses];

export type PutApiCapabilitiesByIdSetStateData = {
    body: AndersonApiApplicationCapabilitiesSetStateCapabilitySetStateCapabilityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/capabilities/{id}/set-state';
};

export type PutApiCapabilitiesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCapabilitiesByIdSetStateError = PutApiCapabilitiesByIdSetStateErrors[keyof PutApiCapabilitiesByIdSetStateErrors];

export type PutApiCapabilitiesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCapabilitiesByIdSetStateResponse = PutApiCapabilitiesByIdSetStateResponses[keyof PutApiCapabilitiesByIdSetStateResponses];

export type DeleteApiCompaniesByIdContactData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        contactId: string;
    };
    url: '/api/companies/{id}/contact';
};

export type DeleteApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiCompaniesByIdContactError = DeleteApiCompaniesByIdContactErrors[keyof DeleteApiCompaniesByIdContactErrors];

export type DeleteApiCompaniesByIdContactResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCompaniesByIdContactData = {
    body: AndersonApiApplicationCompaniesAddContactCompanyAddContactCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/contact';
};

export type PostApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiCompaniesByIdContactError = PostApiCompaniesByIdContactErrors[keyof PostApiCompaniesByIdContactErrors];

export type PostApiCompaniesByIdContactResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PutApiCompaniesByIdContactData = {
    body: AndersonApiApplicationCompaniesUpdateContactCompanyUpdateContactCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/contact';
};

export type PutApiCompaniesByIdContactErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdContactError = PutApiCompaniesByIdContactErrors[keyof PutApiCompaniesByIdContactErrors];

export type PutApiCompaniesByIdContactResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdContactResponse = PutApiCompaniesByIdContactResponses[keyof PutApiCompaniesByIdContactResponses];

export type DeleteApiCompaniesByIdLocationData = {
    body?: never;
    path: {
        id: string;
    };
    query: {
        locationId: string;
    };
    url: '/api/companies/{id}/location';
};

export type DeleteApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiCompaniesByIdLocationError = DeleteApiCompaniesByIdLocationErrors[keyof DeleteApiCompaniesByIdLocationErrors];

export type DeleteApiCompaniesByIdLocationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiCompaniesByIdLocationData = {
    body: AndersonApiApplicationCompaniesAddLocationCompanyAddLocationCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/location';
};

export type PostApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiCompaniesByIdLocationError = PostApiCompaniesByIdLocationErrors[keyof PostApiCompaniesByIdLocationErrors];

export type PostApiCompaniesByIdLocationResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PutApiCompaniesByIdLocationData = {
    body: AndersonApiApplicationCompaniesUpdateLocationCompanyUpdateLocationCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/location';
};

export type PutApiCompaniesByIdLocationErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdLocationError = PutApiCompaniesByIdLocationErrors[keyof PutApiCompaniesByIdLocationErrors];

export type PutApiCompaniesByIdLocationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdLocationResponse = PutApiCompaniesByIdLocationResponses[keyof PutApiCompaniesByIdLocationResponses];

export type GetApiCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type GetApiCompaniesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCompaniesError = GetApiCompaniesErrors[keyof GetApiCompaniesErrors];

export type GetApiCompaniesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationCompaniesCompanyDto>;
};

export type GetApiCompaniesResponse = GetApiCompaniesResponses[keyof GetApiCompaniesResponses];

export type PostApiCompaniesData = {
    body: AndersonApiApplicationCompaniesCreateCompanyCreateCompanyCommand;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type PostApiCompaniesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiCompaniesError = PostApiCompaniesErrors[keyof PostApiCompaniesErrors];

export type PostApiCompaniesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiCompaniesResponse = PostApiCompaniesResponses[keyof PostApiCompaniesResponses];

export type DeleteApiCompaniesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type DeleteApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiCompaniesByIdError = DeleteApiCompaniesByIdErrors[keyof DeleteApiCompaniesByIdErrors];

export type DeleteApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCompaniesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type GetApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCompaniesByIdError = GetApiCompaniesByIdErrors[keyof GetApiCompaniesByIdErrors];

export type GetApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationCompaniesCompanyDto;
};

export type GetApiCompaniesByIdResponse = GetApiCompaniesByIdResponses[keyof GetApiCompaniesByIdResponses];

export type PutApiCompaniesByIdData = {
    body: AndersonApiApplicationCompaniesUpdateCompanyUpdateCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type PutApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdError = PutApiCompaniesByIdErrors[keyof PutApiCompaniesByIdErrors];

export type PutApiCompaniesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdResponse = PutApiCompaniesByIdResponses[keyof PutApiCompaniesByIdResponses];

export type PutApiCompaniesByIdCapabilitiesData = {
    body: AndersonApiApplicationCompaniesSetCapabilitiesCompanySetCapabilitiesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/capabilities';
};

export type PutApiCompaniesByIdCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdCapabilitiesError = PutApiCompaniesByIdCapabilitiesErrors[keyof PutApiCompaniesByIdCapabilitiesErrors];

export type PutApiCompaniesByIdCapabilitiesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdCapabilitiesResponse = PutApiCompaniesByIdCapabilitiesResponses[keyof PutApiCompaniesByIdCapabilitiesResponses];

export type PutApiCompaniesByIdHeadOfficeData = {
    body: AndersonApiApplicationCompaniesSetHeadOfficeCompanySetHeadOfficeCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/head-office';
};

export type PutApiCompaniesByIdHeadOfficeErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdHeadOfficeError = PutApiCompaniesByIdHeadOfficeErrors[keyof PutApiCompaniesByIdHeadOfficeErrors];

export type PutApiCompaniesByIdHeadOfficeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdHeadOfficeResponse = PutApiCompaniesByIdHeadOfficeResponses[keyof PutApiCompaniesByIdHeadOfficeResponses];

export type PutApiCompaniesByIdIndustriesData = {
    body: AndersonApiApplicationCompaniesSetIndustriesCompanySetIndustriesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/industries';
};

export type PutApiCompaniesByIdIndustriesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdIndustriesError = PutApiCompaniesByIdIndustriesErrors[keyof PutApiCompaniesByIdIndustriesErrors];

export type PutApiCompaniesByIdIndustriesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdIndustriesResponse = PutApiCompaniesByIdIndustriesResponses[keyof PutApiCompaniesByIdIndustriesResponses];

export type PutApiCompaniesByIdServiceTypesData = {
    body: AndersonApiApplicationCompaniesSetServiceTypesCompanySetServiceTypesCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/service-types';
};

export type PutApiCompaniesByIdServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdServiceTypesError = PutApiCompaniesByIdServiceTypesErrors[keyof PutApiCompaniesByIdServiceTypesErrors];

export type PutApiCompaniesByIdServiceTypesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdServiceTypesResponse = PutApiCompaniesByIdServiceTypesResponses[keyof PutApiCompaniesByIdServiceTypesResponses];

export type PutApiCompaniesByIdSetStateData = {
    body: AndersonApiApplicationCompaniesSetStateCompanySetStateCompanyCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}/set-state';
};

export type PutApiCompaniesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCompaniesByIdSetStateError = PutApiCompaniesByIdSetStateErrors[keyof PutApiCompaniesByIdSetStateErrors];

export type PutApiCompaniesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCompaniesByIdSetStateResponse = PutApiCompaniesByIdSetStateResponses[keyof PutApiCompaniesByIdSetStateResponses];

export type GetApiCountriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/countries';
};

export type GetApiCountriesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCountriesError = GetApiCountriesErrors[keyof GetApiCountriesErrors];

export type GetApiCountriesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationCountriesCountryDto>;
};

export type GetApiCountriesResponse = GetApiCountriesResponses[keyof GetApiCountriesResponses];

export type PostApiCountriesData = {
    body: AndersonApiApplicationCountriesCreateCountryCreateCountryCommand;
    path?: never;
    query?: never;
    url: '/api/countries';
};

export type PostApiCountriesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiCountriesError = PostApiCountriesErrors[keyof PostApiCountriesErrors];

export type PostApiCountriesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiCountriesResponse = PostApiCountriesResponses[keyof PostApiCountriesResponses];

export type DeleteApiCountriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type DeleteApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiCountriesByIdError = DeleteApiCountriesByIdErrors[keyof DeleteApiCountriesByIdErrors];

export type DeleteApiCountriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiCountriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type GetApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiCountriesByIdError = GetApiCountriesByIdErrors[keyof GetApiCountriesByIdErrors];

export type GetApiCountriesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationCountriesCountryDto;
};

export type GetApiCountriesByIdResponse = GetApiCountriesByIdResponses[keyof GetApiCountriesByIdResponses];

export type PutApiCountriesByIdData = {
    body: AndersonApiApplicationCountriesUpdateCountryUpdateCountryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}';
};

export type PutApiCountriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCountriesByIdError = PutApiCountriesByIdErrors[keyof PutApiCountriesByIdErrors];

export type PutApiCountriesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCountriesByIdResponse = PutApiCountriesByIdResponses[keyof PutApiCountriesByIdResponses];

export type PutApiCountriesByIdSetStateData = {
    body: AndersonApiApplicationCountriesSetStateCountrySetStateCountryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/countries/{id}/set-state';
};

export type PutApiCountriesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiCountriesByIdSetStateError = PutApiCountriesByIdSetStateErrors[keyof PutApiCountriesByIdSetStateErrors];

export type PutApiCountriesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiCountriesByIdSetStateResponse = PutApiCountriesByIdSetStateResponses[keyof PutApiCountriesByIdSetStateResponses];

export type GetApiIndustriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type GetApiIndustriesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiIndustriesError = GetApiIndustriesErrors[keyof GetApiIndustriesErrors];

export type GetApiIndustriesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationIndustriesIndustryDto>;
};

export type GetApiIndustriesResponse = GetApiIndustriesResponses[keyof GetApiIndustriesResponses];

export type PostApiIndustriesData = {
    body: AndersonApiApplicationIndustriesCreateIndustryCreateIndustryCommand;
    path?: never;
    query?: never;
    url: '/api/industries';
};

export type PostApiIndustriesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiIndustriesError = PostApiIndustriesErrors[keyof PostApiIndustriesErrors];

export type PostApiIndustriesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiIndustriesResponse = PostApiIndustriesResponses[keyof PostApiIndustriesResponses];

export type DeleteApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type DeleteApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiIndustriesByIdError = DeleteApiIndustriesByIdErrors[keyof DeleteApiIndustriesByIdErrors];

export type DeleteApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiIndustriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type GetApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiIndustriesByIdError = GetApiIndustriesByIdErrors[keyof GetApiIndustriesByIdErrors];

export type GetApiIndustriesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationIndustriesIndustryDto;
};

export type GetApiIndustriesByIdResponse = GetApiIndustriesByIdResponses[keyof GetApiIndustriesByIdResponses];

export type PutApiIndustriesByIdData = {
    body: AndersonApiApplicationIndustriesUpdateIndustryUpdateIndustryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}';
};

export type PutApiIndustriesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiIndustriesByIdError = PutApiIndustriesByIdErrors[keyof PutApiIndustriesByIdErrors];

export type PutApiIndustriesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiIndustriesByIdResponse = PutApiIndustriesByIdResponses[keyof PutApiIndustriesByIdResponses];

export type PutApiIndustriesByIdSetStateData = {
    body: AndersonApiApplicationIndustriesSetStateIndustrySetStateIndustryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/industries/{id}/set-state';
};

export type PutApiIndustriesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiIndustriesByIdSetStateError = PutApiIndustriesByIdSetStateErrors[keyof PutApiIndustriesByIdSetStateErrors];

export type PutApiIndustriesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiIndustriesByIdSetStateResponse = PutApiIndustriesByIdSetStateResponses[keyof PutApiIndustriesByIdSetStateResponses];

export type GetApiOppertunitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/oppertunities';
};

export type GetApiOppertunitiesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiOppertunitiesError = GetApiOppertunitiesErrors[keyof GetApiOppertunitiesErrors];

export type GetApiOppertunitiesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationOppertunitiesOppertunityDto>;
};

export type GetApiOppertunitiesResponse = GetApiOppertunitiesResponses[keyof GetApiOppertunitiesResponses];

export type PostApiOppertunitiesData = {
    body: AndersonApiApplicationOppertunitiesCreateOppertunityCreateOppertunityCommand;
    path?: never;
    query?: never;
    url: '/api/oppertunities';
};

export type PostApiOppertunitiesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiOppertunitiesError = PostApiOppertunitiesErrors[keyof PostApiOppertunitiesErrors];

export type PostApiOppertunitiesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiOppertunitiesResponse = PostApiOppertunitiesResponses[keyof PostApiOppertunitiesResponses];

export type DeleteApiOppertunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}';
};

export type DeleteApiOppertunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiOppertunitiesByIdError = DeleteApiOppertunitiesByIdErrors[keyof DeleteApiOppertunitiesByIdErrors];

export type DeleteApiOppertunitiesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiOppertunitiesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}';
};

export type GetApiOppertunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiOppertunitiesByIdError = GetApiOppertunitiesByIdErrors[keyof GetApiOppertunitiesByIdErrors];

export type GetApiOppertunitiesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationOppertunitiesOppertunityDto;
};

export type GetApiOppertunitiesByIdResponse = GetApiOppertunitiesByIdResponses[keyof GetApiOppertunitiesByIdResponses];

export type PutApiOppertunitiesByIdData = {
    body: AndersonApiApplicationOppertunitiesUpdateOppertunityUpdateOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}';
};

export type PutApiOppertunitiesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdError = PutApiOppertunitiesByIdErrors[keyof PutApiOppertunitiesByIdErrors];

export type PutApiOppertunitiesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdResponse = PutApiOppertunitiesByIdResponses[keyof PutApiOppertunitiesByIdResponses];

export type PutApiOppertunitiesByIdCapabilitiesData = {
    body: AndersonApiApplicationOppertunitiesSetCapabilitiesOppertunitySetCapabilitiesOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/capabilities';
};

export type PutApiOppertunitiesByIdCapabilitiesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdCapabilitiesError = PutApiOppertunitiesByIdCapabilitiesErrors[keyof PutApiOppertunitiesByIdCapabilitiesErrors];

export type PutApiOppertunitiesByIdCapabilitiesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdCapabilitiesResponse = PutApiOppertunitiesByIdCapabilitiesResponses[keyof PutApiOppertunitiesByIdCapabilitiesResponses];

export type PutApiOppertunitiesByIdIndustriesData = {
    body: AndersonApiApplicationOppertunitiesSetIndustriesOppertunitySetIndustriesOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/industries';
};

export type PutApiOppertunitiesByIdIndustriesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdIndustriesError = PutApiOppertunitiesByIdIndustriesErrors[keyof PutApiOppertunitiesByIdIndustriesErrors];

export type PutApiOppertunitiesByIdIndustriesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdIndustriesResponse = PutApiOppertunitiesByIdIndustriesResponses[keyof PutApiOppertunitiesByIdIndustriesResponses];

export type PutApiOppertunitiesByIdInterestedPartnersData = {
    body: AndersonApiApplicationOppertunitiesSetInterestedPartnersOppertunitySetInterestedPartnersOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/interested-partners';
};

export type PutApiOppertunitiesByIdInterestedPartnersErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdInterestedPartnersError = PutApiOppertunitiesByIdInterestedPartnersErrors[keyof PutApiOppertunitiesByIdInterestedPartnersErrors];

export type PutApiOppertunitiesByIdInterestedPartnersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdInterestedPartnersResponse = PutApiOppertunitiesByIdInterestedPartnersResponses[keyof PutApiOppertunitiesByIdInterestedPartnersResponses];

export type PutApiOppertunitiesByIdServiceTypesData = {
    body: AndersonApiApplicationOppertunitiesSetServiceTypesOppertunitySetServiceTypesOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/service-types';
};

export type PutApiOppertunitiesByIdServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdServiceTypesError = PutApiOppertunitiesByIdServiceTypesErrors[keyof PutApiOppertunitiesByIdServiceTypesErrors];

export type PutApiOppertunitiesByIdServiceTypesResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdServiceTypesResponse = PutApiOppertunitiesByIdServiceTypesResponses[keyof PutApiOppertunitiesByIdServiceTypesResponses];

export type PutApiOppertunitiesByIdSetStateData = {
    body: AndersonApiApplicationOppertunitiesSetStateOppertunitySetStateOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/set-state';
};

export type PutApiOppertunitiesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdSetStateError = PutApiOppertunitiesByIdSetStateErrors[keyof PutApiOppertunitiesByIdSetStateErrors];

export type PutApiOppertunitiesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdSetStateResponse = PutApiOppertunitiesByIdSetStateResponses[keyof PutApiOppertunitiesByIdSetStateResponses];

export type PutApiOppertunitiesByIdStatusData = {
    body: AndersonApiApplicationOppertunitiesSetStatusOppertunitySetStatusOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/status';
};

export type PutApiOppertunitiesByIdStatusErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdStatusError = PutApiOppertunitiesByIdStatusErrors[keyof PutApiOppertunitiesByIdStatusErrors];

export type PutApiOppertunitiesByIdStatusResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdStatusResponse = PutApiOppertunitiesByIdStatusResponses[keyof PutApiOppertunitiesByIdStatusResponses];

export type PutApiOppertunitiesByIdFullData = {
    body: AndersonApiApplicationOppertunitiesUpdateFullOppertunityUpdateFullOppertunityCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunities/{id}/full';
};

export type PutApiOppertunitiesByIdFullErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunitiesByIdFullError = PutApiOppertunitiesByIdFullErrors[keyof PutApiOppertunitiesByIdFullErrors];

export type PutApiOppertunitiesByIdFullResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunitiesByIdFullResponse = PutApiOppertunitiesByIdFullResponses[keyof PutApiOppertunitiesByIdFullResponses];

export type GetApiOppertunityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/oppertunity-types';
};

export type GetApiOppertunityTypesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiOppertunityTypesError = GetApiOppertunityTypesErrors[keyof GetApiOppertunityTypesErrors];

export type GetApiOppertunityTypesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationOppertunityTypesOppertunityTypeDto>;
};

export type GetApiOppertunityTypesResponse = GetApiOppertunityTypesResponses[keyof GetApiOppertunityTypesResponses];

export type PostApiOppertunityTypesData = {
    body: AndersonApiApplicationOppertunityTypesCreateOppertunityTypeCreateOppertunityTypeCommand;
    path?: never;
    query?: never;
    url: '/api/oppertunity-types';
};

export type PostApiOppertunityTypesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiOppertunityTypesError = PostApiOppertunityTypesErrors[keyof PostApiOppertunityTypesErrors];

export type PostApiOppertunityTypesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiOppertunityTypesResponse = PostApiOppertunityTypesResponses[keyof PostApiOppertunityTypesResponses];

export type DeleteApiOppertunityTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunity-types/{id}';
};

export type DeleteApiOppertunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiOppertunityTypesByIdError = DeleteApiOppertunityTypesByIdErrors[keyof DeleteApiOppertunityTypesByIdErrors];

export type DeleteApiOppertunityTypesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiOppertunityTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunity-types/{id}';
};

export type GetApiOppertunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiOppertunityTypesByIdError = GetApiOppertunityTypesByIdErrors[keyof GetApiOppertunityTypesByIdErrors];

export type GetApiOppertunityTypesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationOppertunityTypesOppertunityTypeDto;
};

export type GetApiOppertunityTypesByIdResponse = GetApiOppertunityTypesByIdResponses[keyof GetApiOppertunityTypesByIdResponses];

export type PutApiOppertunityTypesByIdData = {
    body: AndersonApiApplicationOppertunityTypesUpdateOppertunityTypeUpdateOppertunityTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunity-types/{id}';
};

export type PutApiOppertunityTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunityTypesByIdError = PutApiOppertunityTypesByIdErrors[keyof PutApiOppertunityTypesByIdErrors];

export type PutApiOppertunityTypesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunityTypesByIdResponse = PutApiOppertunityTypesByIdResponses[keyof PutApiOppertunityTypesByIdResponses];

export type PutApiOppertunityTypesByIdSetStateData = {
    body: AndersonApiApplicationOppertunityTypesSetStateOppertunityTypeSetStateOppertunityTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/oppertunity-types/{id}/set-state';
};

export type PutApiOppertunityTypesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiOppertunityTypesByIdSetStateError = PutApiOppertunityTypesByIdSetStateErrors[keyof PutApiOppertunityTypesByIdSetStateErrors];

export type PutApiOppertunityTypesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOppertunityTypesByIdSetStateResponse = PutApiOppertunityTypesByIdSetStateResponses[keyof PutApiOppertunityTypesByIdSetStateResponses];

export type GetApiRegionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/regions';
};

export type GetApiRegionsErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiRegionsError = GetApiRegionsErrors[keyof GetApiRegionsErrors];

export type GetApiRegionsResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationRegionsRegionDto>;
};

export type GetApiRegionsResponse = GetApiRegionsResponses[keyof GetApiRegionsResponses];

export type PostApiRegionsData = {
    body: AndersonApiApplicationRegionsCreateRegionCreateRegionCommand;
    path?: never;
    query?: never;
    url: '/api/regions';
};

export type PostApiRegionsErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiRegionsError = PostApiRegionsErrors[keyof PostApiRegionsErrors];

export type PostApiRegionsResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiRegionsResponse = PostApiRegionsResponses[keyof PostApiRegionsResponses];

export type DeleteApiRegionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type DeleteApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiRegionsByIdError = DeleteApiRegionsByIdErrors[keyof DeleteApiRegionsByIdErrors];

export type DeleteApiRegionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiRegionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type GetApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiRegionsByIdError = GetApiRegionsByIdErrors[keyof GetApiRegionsByIdErrors];

export type GetApiRegionsByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationRegionsRegionDto;
};

export type GetApiRegionsByIdResponse = GetApiRegionsByIdResponses[keyof GetApiRegionsByIdResponses];

export type PutApiRegionsByIdData = {
    body: AndersonApiApplicationRegionsUpdateRegionUpdateRegionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}';
};

export type PutApiRegionsByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiRegionsByIdError = PutApiRegionsByIdErrors[keyof PutApiRegionsByIdErrors];

export type PutApiRegionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiRegionsByIdResponse = PutApiRegionsByIdResponses[keyof PutApiRegionsByIdResponses];

export type PutApiRegionsByIdSetStateData = {
    body: AndersonApiApplicationRegionsSetStateRegionSetStateRegionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/regions/{id}/set-state';
};

export type PutApiRegionsByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiRegionsByIdSetStateError = PutApiRegionsByIdSetStateErrors[keyof PutApiRegionsByIdSetStateErrors];

export type PutApiRegionsByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiRegionsByIdSetStateResponse = PutApiRegionsByIdSetStateResponses[keyof PutApiRegionsByIdSetStateResponses];

export type GetApiServiceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/service-types';
};

export type GetApiServiceTypesErrors = {
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiServiceTypesError = GetApiServiceTypesErrors[keyof GetApiServiceTypesErrors];

export type GetApiServiceTypesResponses = {
    /**
     * OK
     */
    200: Array<AndersonApiApplicationServiceTypesServiceTypeDto>;
};

export type GetApiServiceTypesResponse = GetApiServiceTypesResponses[keyof GetApiServiceTypesResponses];

export type PostApiServiceTypesData = {
    body: AndersonApiApplicationServiceTypesCreateServiceTypeCreateServiceTypeCommand;
    path?: never;
    query?: never;
    url: '/api/service-types';
};

export type PostApiServiceTypesErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PostApiServiceTypesError = PostApiServiceTypesErrors[keyof PostApiServiceTypesErrors];

export type PostApiServiceTypesResponses = {
    /**
     * Created
     */
    201: AndersonApiApiControllersResponseTypesJsonResponseOfSystemGuid;
};

export type PostApiServiceTypesResponse = PostApiServiceTypesResponses[keyof PostApiServiceTypesResponses];

export type DeleteApiServiceTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type DeleteApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type DeleteApiServiceTypesByIdError = DeleteApiServiceTypesByIdErrors[keyof DeleteApiServiceTypesByIdErrors];

export type DeleteApiServiceTypesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiServiceTypesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type GetApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type GetApiServiceTypesByIdError = GetApiServiceTypesByIdErrors[keyof GetApiServiceTypesByIdErrors];

export type GetApiServiceTypesByIdResponses = {
    /**
     * OK
     */
    200: AndersonApiApplicationServiceTypesServiceTypeDto;
};

export type GetApiServiceTypesByIdResponse = GetApiServiceTypesByIdResponses[keyof GetApiServiceTypesByIdResponses];

export type PutApiServiceTypesByIdData = {
    body: AndersonApiApplicationServiceTypesUpdateServiceTypeUpdateServiceTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}';
};

export type PutApiServiceTypesByIdErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiServiceTypesByIdError = PutApiServiceTypesByIdErrors[keyof PutApiServiceTypesByIdErrors];

export type PutApiServiceTypesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiServiceTypesByIdResponse = PutApiServiceTypesByIdResponses[keyof PutApiServiceTypesByIdResponses];

export type PutApiServiceTypesByIdSetStateData = {
    body: AndersonApiApplicationServiceTypesSetStateServiceTypeSetStateServiceTypeCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/service-types/{id}/set-state';
};

export type PutApiServiceTypesByIdSetStateErrors = {
    /**
     * Bad Request
     */
    400: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Not Found
     */
    404: MicrosoftAspNetCoreMvcProblemDetails;
    /**
     * Internal Server Error
     */
    500: MicrosoftAspNetCoreMvcProblemDetails;
};

export type PutApiServiceTypesByIdSetStateError = PutApiServiceTypesByIdSetStateErrors[keyof PutApiServiceTypesByIdSetStateErrors];

export type PutApiServiceTypesByIdSetStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiServiceTypesByIdSetStateResponse = PutApiServiceTypesByIdSetStateResponses[keyof PutApiServiceTypesByIdSetStateResponses];
